### ISSUE TITLE
My levels won't build

### ISSUE THREAD

**Issue by MERNY** [BEEmod/BEE2.4#1009]
When I have BEE2 installed, my levels wont build. It says: PermissionError: [WinError 5] Access is denied: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\sdk_content\\maps\\tmp_14' -> 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\sdk_content\\maps\\preview.bsp'
I tried changing the permissions, but that didn't do anything. Can you help as soon as you can?

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by MERNY** [comment]
It worked for a little bit, but then it stopped working again. Maybe it's the antivirus? I have Malwarebytes and Norton Security Center.

**Comment by LautaroL20** [comment]
Well, that is why on Step N°1 it says: " Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the bin folder inside the Portal 2 game´s directory. Just add the whole bin folder in your antivirus exception´s list, because otherwise this can cause a "building error" issue when building your puzzle."

**Comment by MERNY** [comment]
Whoops, I meant McAfee Security Center... In Security Center, you can't select folders sadly. How am I supposed to exclude all of the bin files
![screenshot 4](https://user-images.githubusercontent.com/44384404/47538557-a41cab80-d891-11e8-84b8-2300353838b3.png)

**Comment by LautaroL20** [comment]
What a limted antivirus... then you will have to hold the left CTRL and then select with the mouse each file of that folder.

**Comment by ZombiePwner1** [comment]
@LautaroL20 All anti-viruses don't allow you to select file folders if I'm not wrong. BTW get on steam.

**Comment by MERNY** [comment]
MalwareBytes lets you select folders

**Comment by MERNY** [comment]
To use BEE2, I just turn scanning off for like 60 mins, then I edit away. Thanks for the help!

**Comment by LautaroL20** [comment]
I am glad to know i was right about the fact that the antivirus was the cause of those building errors you were getting at using Beemod and not the mod itself.
