### ISSUE TITLE
P1 piston reflections aren't working

### ISSUE THREAD

**Issue by Cookiejae** [BEEmod/BEE2.4#1016]
Um?
Has this ever happened to anyone?https://cdn.discordapp.com/attachments/369159415552802826/509140866800156673/unknown.png
Does anyone know a fix? Please tell me.

**Comment by ZombiePwner1** [comment]
@Cookiejae This is due to portal 2 rendering certain textures differently compared to portal 1 and because of this a custom texture needs to be used however it seems the custom texture is not working.

**Comment by Cookiejae** [comment]
Is there a solution?

**Comment by Cookiejae** [comment]
and when is that gonna come out?

**Comment by ZombiePwner1** [comment]
@Cookiejae Release 30 just recently came out so not for awhile.

**Comment by Cookiejae** [comment]
Well, how long does a release usually take?

**Comment by LautaroL20** [comment]
No, there will not be a solution since actually there isn´t anything we can do to fix how the Source Engine renders the game textures.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.

This issue was moved to the item´s page, here: https://github.com/BEEmod/BEE2-items/issues/2854

**Comment by ZombiePwner1** [comment]
@LautaroL20 I already told him he posted in the wrong section. Get on steam aswell.
