### ISSUE TITLE
aperture tag glitch

### ISSUE THREAD

**Issue by wimklaver** [BEEmod/BEE2.4#1026]
video says it all:
https://www.youtube.com/watch?v=WluFhuF9ohc&feature=youtu.be

**Comment by ZombiePwner1** [comment]
Seems that you are for some reason spawning with a portal gun that has portals enabled when it shouldn't. Also your posting in the wrong section. Please post in BEE2-Items and not in BEE2.4 since this is for the main programs interface.

**Comment by LautaroL20** [comment]
@Konclan - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
