### ISSUE TITLE
How to upgrade to BEE2 pre31 from BEE2 pre29?

### ISSUE THREAD

**Issue by MeloettaRules28** [BEEmod/BEE2.4#1032]
I kind of forgot how since I forgot about this game and this app, and now I see that pre31 is here.
So, how do I upgrade to the new one from my pre29?
(The game IS bought from Steam.)

**Comment by LautaroL20** [comment]
Get rid entirely from the PRL29 by deleting their folders where you installed it. Each pre-release is abolutely independent from each other, no need to mixing them, otherwise youll experperiment issues. Once you downloaded PRL31, follow these steps carefully:

Introduction: when using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by MeloettaRules28** [comment]
Ok, thank you!

**Comment by Konclan** [comment]
I mean I'd just recommend the "Uninstall from selected game" in the "files" drop-down menu. Instead of risking old files breaking new stuff.

**Comment by TeamSpen210** [comment]
@LautaroL20, can you stop posting the big uninstall and verify thing? It shouldn't be a problem anymore, I fixed it long ago. And if it is, I need to fix the bug.
