### ISSUE TITLE
Fail to compile.

### ISSUE THREAD

**Issue by Veritius** [BEEmod/BEE2.4#1037]
Thanks, TeamSpen210, you've been REALLY helpful. (please note, sarcasm)
So, regardless of having BEEmod objects in the map, only happening when BEEmod is installed at all, the map fails to compile.

It generates geometry, stopping for a few seconds just a few pixels from the end, then it goes to the next bar, goes really fast to the middle, and then gives me a generic error message.

This happens with the latest release (4.32.0) and PR29 (and the appropriate packages), the versions I've tested. (Running on the Portal 2 version that existed during the date of making this post) It appears that all the BEEmod models and images failed to be found. The Items tab in the puzzle editor have missing-texture images in place of all BEEmod items. Errors appear wherever the modded model is (fizzler mod fields still appear) and once it broke the game and I couldn't launch it again. In total, I've re-downloaded Portal 2 three times before I realised I should just back it up, because I'm an idiot.

You might want to have a look at the console logs, if you want to see what I mean.

Console Logs:
PR29: https://pastebin.com/994wLmg9
4.32.0: https://pastebin.com/E7wyHcwX

**Comment by LautaroL20** [comment]
Try doing the following carefully, and see if it works:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by LautaroL20** [comment]
Glad i was able to helo you solve your issue at Discord!
