### ISSUE TITLE
I have missing folders when I download the latest version of BEE2

### ISSUE THREAD

**Issue by MERNY** [BEEmod/BEE2.4#1039]
lol xd WHY ARE THERE MISSING FILES???? I want to upload a custom thumbnail for my levels and I got an error... I looked for the file location but I couldn't find it. pls help

**Comment by Dylwan** [comment]
That's because the developers made a mistake and did not include the **CONFIG** directory inside the BEE2 folder.

- You should create a folder named "config" inside BEE2's folder (Or any other name if it's not BEE2 exactly).

- ![image](https://user-images.githubusercontent.com/34210449/50372035-17f3df80-05c7-11e9-87bc-f18dec699d07.png)

BEE2 is the folder i named for BEE2's contents. CONFIG is where the custom thumbnail would be stored. SCREENSHOT.JPG is the stored custom thumbnail, but optional.

I hope this helps, kind regards from Dylwan.
