### ISSUE TITLE
New Color for Reflection Gel

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2.4#1045]
Reflection gel should be changed to be a different color. It is the same color as conversion gel which may confuse players who are unfamiliar with the gel. Also, this makes it difficult to make test chambers that use both conversion and reflection gels. I was thinking reflection gel could be a light red color.

**Comment by Luke18033** [comment]
Reflection Gel painted on a surface is hardcoded to use the same color as Conversion Gel (`portal_paint_color`). We can change the color of the blobs though, which has been done, making them a dark gray.

This is also a [BEE2-items](https://github.com/BEEmod/BEE2-items) issue.

**Comment by Luke18033** [comment]
Go in that map and spawn a blob of Conversion Gel, see what happens.

Also, [adhesion gel is green](https://youtu.be/o73-sbjg8k0).

**Comment by ZombiePwner1** [comment]
@Luke18033 Adhesion gel was never green. It was purple during the time it was still in the game since the surface texture was purple.

**Comment by Luke18033** [comment]
Officially, Adhesion Gel isn't any color. Purple was implemented as a placeholder during development - the gel was cut before they decided on a final color. That means mod/map developers are free to use whatever color they want for the gel, whether it be the placeholder purple color or something completely different. Additionally, green is just a more logical color for Adhesion Gel - it implies "sticky", and is more distinct from the existing gels. That's why they decided to use that color in Desolation (which you should [check out](https://moddb.com/mods/desolation) if you haven't already, by the way).

Regardless, this isn't something I really want to argue about, especially in the comments of a random GitHub issue. Just look at the Desolation Q&A and the comments of the demonstration video, the developers did a much better job of explaining this than I did.
