### ISSUE TITLE
Feature Suggestions, division fields, TNT Turrets, Destructible glass & Adhesion Gel

### ISSUE THREAD

**Issue by CS117** [BEEmod/BEE2.4#1089]
- It would be cool to see the surface division fields from the penrose puzzles, which would create portals to other rooms. I dunno if it would be possible due to how complicated linking 2 fields together could be, but it would be cool to have those bad-boys seen in the workshop more.

- TNT turrets & Destructible glass should also be implemented, considering that destructible glass is already present in P2's story modes, it would be very interesting to add puzzle elements that would require breaking glass.

- finally, adhesion gel would also be cool (i'm not good at adding explainations to lists that dont sound repetitive/vague)

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Comment by LautaroL20** [comment]
Also, you are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
