### ISSUE TITLE
Co-op mode - can pass cubes to each other through gratings

### ISSUE THREAD

**Issue by Venima** [BEEmod/BEE2.4#1094]
This seems to happen in vanilla portal 2 as well, but I was just wondering if this is possible to fix...
Note I've only tried BeeMod 2.4.0 pr29 or ealier, so I don't know if more recent versions have fixed this or not; I apologise if they have.

Reproduction steps:

1. Create map with cube & large grating that can be walked around.
2. Player 1 pick up cube and walk right up to the grating (while holding cube).
3. Player 2 walk to the opposite side of the grating and press E on the cube held by Player 1.

Notice that the cube has exchanged hands by passing through the grating.

**Comment by LautaroL20** [comment]
Ive made an item called "Working Coop Grates" that solves this issue, it is already available in Beemod since the pre-release 27.

![Working Coop Grates by Lautaro](https://user-images.githubusercontent.com/12244376/55117232-cf1d5c80-50c8-11e9-8aa9-92da7173bba9.png)

Actually, we are reaching the release number 34, so i highly suggest to upgrade to get all new features and items that were made during the last period. Download links:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1
Packages:  https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0

**Comment by Venima** [comment]
Oh lord, how did I miss these?! Awesome! Thanks for letting me know and showing an image, that helped me find it in the item list!

**Comment by LautaroL20** [comment]
No problem.
