### ISSUE TITLE
Blue Errors And Texture Problem

### ISSUE THREAD

**Issue by nicktrainfan1550** [BEEmod/BEE2.4#1100]
BLUE ERROR: https://gyazo.com/69576bc6f7812484b26249020eea6727
MISSING ITEM TEXTURES: https://gyazo.com/057615c4c7c517686306fdd63ba25bc8

Okay so. I downloaded BEE Mod 2.4 and i am having issues with it. The Models of the ones are Missing as they are blue errors. Can somebody help me how to fix this please?

**Comment by LautaroL20** [comment]
In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!
