### ISSUE TITLE
A few requested features

### ISSUE THREAD

**Issue by V0pT** [BEEmod/BEE2.4#1133]
These aren't REALLY big problems, I just think they would be kind of useful. 

1: There aren't any voicelines that relate to escaping at all. I'm making a testing track and during the escape sequence I've kind of just turned voicelines off because there isn't any good ones to use for, well, escaping. 

2: There's different styles of doors in the game, and one thing I would REALLY love is if they were independent of the style setting, meaning you could change the type of door in the level editor. Either that or having an "escape" style where the entry is normal clean and the exit is more of a factory, it just makes for a cleaner transition.

3: A help mode to explain to new users how to use all the different features. For instance, how to connect vactubes or catwalks, or other things like that. A good alternative would be to just have a link to the wiki in the app.

4: An update to rocket turrets, bombs, and breakable windows. I'm very new to BEE2, so I don't know if any of these are already in the works or anything but right now rocket turrets are completely useless. They lock on, but they lock on 2 feet below you, the missile is invisible, no missile noise is made, and half the time they don't even shoot. I tried to go and replace them with bombs, but no bombs appear in the item catalogue. Also, when I DID manage to get the rocket turret to shoot at the window, it didn't break.

5: A search function. This would be SO helpful at finding items. Right now there's just a bunch of gray text in brackets with item categories that doesn't seem to format correctly. Adding a search function to search for items would be incredibly helpful.

**Comment by Luke18033** [comment]
[Don't combine suggestions.](https://github.com/BEEmod/BEE2-items/blob/master/.github/contributing.md) 

1. BEE2 isn't really meant to be used for stories/map series, although a BTS Wheatley voice pack was suggested in BEEmod/BEE2-items#827...
2. ...And I did suggest BTS transition corridors in BEEmod/BEE2-items#607, which could be used for this. I might close that issue though because I don't really think it's necessary anymore.
3. You can already find help on items by right-clicking them in the app, or on the [wiki](https://github.com/BEEmod/BEE2-items/wiki).
4. Rocket turrets are generally buggy in P2, getting it to work correctly is not easy. Bombs and breakable glass are planned.
5. A search option would be nice. The tags are pretty useless, they should probably be removed.
