### ISSUE TITLE
updating process didn't work

### ISSUE THREAD

**Issue by MERNY** [BEEmod/BEE2.4#1135]
I followed all of the steps and it still didn't seem to load in all textures... Are there any ways I can troubleshoot this?

**Comment by LautaroL20** [comment]
If afther following the steps from below it doesn't work, then pray...

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by ZombiePwner1** [comment]
@LautaroL20 Got your new CPU?

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Yes, but it seems that the problem was not in the CPU, but it could be the Motherboad or the Power Supply which could not be giving the correct voltages, so i will still have to wait another week or even a second one. Glad at least i have this potato pc to see a few websites but still its terrible inefficient.

**Comment by ZombiePwner1** [comment]
@LautaroL20 ... Just when I want you to test one of my maps and I have to wait another 2 weeks or something.

**Comment by ZombiePwner1** [comment]
Try to see if you can use the steam website @LautaroL20

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I will try using steam website but later, since i need to sleep now. We have different schedules as we are living in totally different continents.
