### ISSUE TITLE
Game naming dialog uses incorrect button style

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1148]
The game naming dialog uses the "classic" button style:
![image](https://user-images.githubusercontent.com/19228201/61075032-fc6aed80-a3cd-11e9-8f7a-a6cc92a89b3c.png)
This is inconsistent with every other UI in the app, which uses the modern style:
![image](https://user-images.githubusercontent.com/19228201/61075244-65526580-a3ce-11e9-889b-bc1c2583c766.png)

**Comment by JavierNovellon** [comment]
Trying to help here, but this might as well be a Windows UI problem. I say this because BEEmod is not the first program I've seen do something similar.

My guess is, when they redesigned it for Windows Vista, Microsoft must've forgotten to (or intentionally didn't) chage certain types of dialog windows that may have been old or unused at the time. If this is to be true, then it simply has been carried ever since: Windows Vista, Windows 7, Windows 8 and 8.1, and now, Windows 10.

Point is, if true, BEEmod just happens to be requesting an older dialog box that Microsoft forgot to redesign. It may not be fixable, because it may not be BEEmod's fault.

**Comment by Luke18033** [comment]
This also affects the save palette dialog.
![image](https://user-images.githubusercontent.com/19228201/63644340-1883cf00-c69c-11e9-8867-a14d2b5c9b7d.png)

**Comment by LautaroL20** [comment]
You probably should edit your original post and add that picture in it, because its probably that most of the time, the comment section is not viewed at the time of checking an issue to fixing it, beyond the description inside the original post.

**Comment by TeamSpen210** [comment]
Both those dialogs use the same code, so fixing one would fix both. There's probably a few other places it's used. They're actually builtin to `tkinter`, so I suppose it's an issue with that. Maybe I should see if I can do something custom...

**Comment by TeamSpen210** [comment]
Ok, they should probably be switched to use `idlelib.query.Query()`.
