### ISSUE TITLE
Windows Defender Considers bee2.exe a Virus

### ISSUE THREAD

**Issue by OmGCHOOCHOOTRAIN** [BEEmod/BEE2.4#1214]
For some reason, after the latest update, Windows Defender found a Trojan Fuerboos.C!Cl virus inside the executable. I  believe this is not intentional, but this needs to be fixed _immediately_! Viruses are **NOT SAFE!**

A possible cause is BEEmod Music Changer, as a Google Virus Scan found it "uncommonly downloaded and dangerous".

**Comment by Luke18033** [comment]
Infrequently downloaded =/= virus. Read the FAQ.

**Comment by LautaroL20** [comment]
@OmGCHOOCHOOTRAIN - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.
