### ISSUE TITLE
Automatically hide voice packs with no lines

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1245]
A few voice packs (P1 GLaDOS in particular) currently do not have any lines, leading lots of people to ask on Discord why the lines aren't appearing/playing. We don't want to remove the packs though, since the plan is to eventually fix them. An appropriate solution would be to have the app automatically detect empty voice packs, and skip over them or hide them from the UI. Once the lines were added, everything would automatically start appearing again as normal.

**Comment by supersean08-pro** [comment]
isn't the portal 1 glados voice "text to speech"?

**Comment by CheezyPig** [comment]
No?

**Comment by Flash4433** [comment]
> isn't the portal 1 glados voice "text to speech"?
No. She's voiced by Ellen McLain. You can find more about how they did her voice here. https://en.wikipedia.org/wiki/GLaDOS#Voice_design

15.ai can generate custom voice lines for GLaDOS, but they have some problems here and there. Also, https://github.com/BEEmod/BEE2-items/wiki/FAQ#wait-but-15ai-can-generate-custom-voicelines-for-glados-and-wheatley

**Comment by supersean08-pro** [comment]
but in the video called "if portal 2 was written by a bot" doesn't glados speak like text to speech, and doesn't the portal 1 voice sound like that as well?

**Comment by CheezyPig** [comment]
That still has nothing to do with BEEmod..?

**Comment by The-Queen55142** [comment]
Please listen to the P1 lines found [here](https://theportalwiki.com/wiki/GLaDOS_voice_lines)
The inflections and pronunciation of words is far too human to be text to speech. And "If Portal 2 Was Written By A Bot" has nothing to do with the conversation

We cannot add actual P1 lines due to subtitle and language issues

We can't add 15.ai because its got heavy issues, and the same issues as the actual P1 lines.

And Text to Speech sounds horrid. (plus the reasons above)

And thats not even the point of this issue so, back to the topic at hand. This is a great enhancement and i fully approve. Nice work, Luke

**Comment by Luke18033** [comment]
All the empty voice packs have now been removed or properly implemented, I don't think specifically handling this in the app is really needed.
