### ISSUE TITLE
install only needed assets to the game

### ISSUE THREAD

**Issue by Fennecai** [BEEmod/BEE2.4#1249]
suggestion. Currently, beemod installs all the custom assets to the game, even if the current style and items dont use them in any way- this takes up unnecessary space, and may cause confusion for hammer mappers who want to also use beemod for their puzzle prototyping.

I think it would be a good enhancement if beemod was able to uninstall un-needed bee assets/instances/etc. and only install what it will actually use in-game.

this will save the headache for hammer mappers who use beemod where bee assets can easily be mistaken for vanilla assets that look the same, and then used without the due credit and not packed into maps properly as a result. this mostly applies to textures; but some models and other assets may be mistaken as vanilla by mappers who are less familiar with what models and stuff actually came with the base game.

this will also reduce the amount of disk space that beemod takes up within the portal 2 install directory; as it will only need to use the space for files it actually uses, and not copy the files it has no use for with the current configuration.

i do realize this might be more suitable as 2 feature requests instead of one; due to the complexity dynamic uninstalling might add, but dynamic installing alone would be a good enhancement even by itself.

**Comment by Flash4433** [comment]
It would also be nice to have an option in the options tab to disable the auto-unistall, for users that like to have every texture and model installed in Hammer.

**Comment by TeamSpen210** [comment]
This would be pretty time-consuming, since I'd have to go through every item and manually set which resources it specifically uses - the dynamic nature means it can't parse that out of the files. Almost all the resources would end up being copied anyway, it'd just mean you have to keep waiting for it to copy and delete those every time your export. Mistaking the resources isn't really a concern, that's why all of them (minus a few very old ones) have `bee2/` somewhere in the filename.

If you want to reduce disk space, there's actually already a way to do this - go into File → Manage Packages, then disable the items/styles you don't want to use. That will make it not load those and therefore not copy the resources.
