### ISSUE TITLE
Cannot Build Tests with any modifications anymore

### ISSUE THREAD

**Issue by republiccommando1138** [BEEmod/BEE2.4#1252]
When I try to create a test that involves anything in BEEMOD, upon building it, I get the error message that the map could not be built. On top of this, sometimes icons from the palette do not show up, as can be seen in the screenshot below. I have tried verifying the game files (which resets the palette), reinstalling the game, reinstalling BEEMOD, and none of those solutions have been effective. The strange part is that everything was working fine a few months ago, and I had not changed the game's files since then. Any help would be appreciated.

![Screen Shot 2020-02-04 at 8 05 43 PM](https://user-images.githubusercontent.com/58492997/73802028-49f3e100-478a-11ea-80e4-67e0b4985acc.png)

**Comment by ZombiePwner1** [comment]
There is an option in BEE2's settings that stops the program from resetting the game files. If I recall uncheck that on the first installation to let BEE2 install everything and then check it again to stop it resetting files.

**Comment by republiccommando1138** [comment]
I can't find that option anywhere, one thing I forgot to mention is that I'm on Mac, if that helps

**Comment by ZombiePwner1** [comment]
I'm trying to remember what that option was called been quite a long time since I last touched Beemod.

**Comment by LautaroL20** [comment]
@republiccommando1138  In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by republiccommando1138** [comment]
That solution appeared to solve everything. Thanks for the help.

**Comment by LautaroL20** [comment]
No problem.
