### ISSUE TITLE
Antline caused crash

### ISSUE THREAD

**Issue by RAIL17** [BEEmod/BEE2.4#1308]
I managed to repeat this a couple times while working on a map. Basically, I had two buttons connected to an OR gate (The visible type) and that gate connected to 4-5 panels, aligned in such a way that I'd have three to four antlines on a surface, in such a way that connected objects placed on opposite sides of the map would have an antline that would try to cross over that surface, tested with a laser receiver and a cube dropper; this will immediately proceed to crash and close the game.

I believe it's something with the antlines, because when changing the connection display to 'signage', and connecting the two objects, my map didn't crash, but when I changed it back to 'antline', the game closed on the spot. 

From my testing I think it's caused by too many antlines on a surface and the editor unable to display them all, but I don't know how it really works to make a proper assumption on the matter. It **definitively** has something to do with antlines though.

**Comment by Luke18033** [comment]
This is a bug in the editor, we can't fix it.

**Comment by FrozenDragon0** [comment]
My only explanation to this is that the antlines are trying to place themselves in a position that the game considers invalid and in return crashes. The paint gun activation field item has also caused this problem. But as @Luke18033 said we can't do anything about this.

**Comment by Luke18033** [comment]
Specifically, the crash is caused by an item's output antlines being blocked in the same voxel as the item. You can cause it in the vanilla Puzzlemaker by placing a laser catcher on a wall, offsetting it downwards, and connecting it to an item above (so the antline goes out the top). If you then place a light strip in the uppermost position of the same block, the game will crash.
