### ISSUE TITLE
Missing images and models

### ISSUE THREAD

**Issue by PietroLegal** [BEEmod/BEE2.4#1316]
When you look at the custom objects in the toolbar, they are all bugged with the pink and black pattern, and when you put them into the test chamber, they appear as a blue error model. Can someone help me please?

**Comment by ExoBot343** [comment]
Download the packages.

**Comment by A-PENCIL-SHARPENER** [comment]
I am having the same problem.

**Comment by Luke18033** [comment]
Uh, no? Those are selection meshes, used to detect when you mouse over an item in the editor. They'd just be another one of the file types that are missing, they're not the root cause of the problem, and there is a fix. Please don't say things like that unless you actually know what you're talking about.

**Comment by Luke18033** [comment]
@PietroLegal Do you have a `bee2/` folder in your Portal 2 directory? What's in it? That's where all the custom assets are stored, so if it's missing or empty that would explain the problem.

**Comment by Luke18033** [comment]
Closing due to lack of response

**Comment by PietroLegal** [comment]
> @PietroLegal Do you have a `bee2/` folder in your Portal 2 directory? What's in it? That's where all the custom assets are stored, so if it's missing or empty that would explain the problem.
Oh i'm really sorry for not responding, well, i've found the fix by myself, dont worry.
