### ISSUE TITLE
Bug: Doesn't want to export packages

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2.4#1390]
I "uninstalled from selected game" and installed back again to update packages. But, when exporting, "Copy resources" is skipped, while it wasn't even exported in game. In result:
![That's the result](https://user-images.githubusercontent.com/69758777/93016429-5f9f7380-f5c1-11ea-8fd1-666ff3f49333.png)
Bee2 items are not in game.

**Comment by Thedoczek** [comment]
The same thing happens when uninstalled everyhting and installed earlier version in other folder.

How to fix that?

**Comment by Thedoczek** [comment]
It's something only on my PC

**Comment by Flash4433** [comment]
But did you manage to fix it?

**Comment by Thedoczek** [comment]
> But did you manage to fix it?

No,but I know that's file extracter problem.

**Comment by LautaroL20** [comment]
@Thedoczek - In order to solve this issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!
