### ISSUE TITLE
Even with an empty chamber, Beemod will cause "Failure To Compile".

### ISSUE THREAD

**Issue by TeknoStyle555** [BEEmod/BEE2.4#1406]
Since I'm playing Portal 2 with Bee2.4 and using it to create test chambers with it, I've noticed a peculiar rror that seems to occur in the game after loading the test chamber, with or without any elements added to it. It just tells me that there was an error at creating the chamber.

The cause for what I found in the game's console is as follows:

VVIS failed.

Valve Software - vvis.exe (Nov 12 2019)
4 threads
reading d:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
reading d:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt
LoadPortals: couldn't read d:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt

I don't know if this is a bug that the mod author has to be aware of, or if my game's messing up. Either way, I'd like someone to help me with this. Please, I don't want to encounter such a problem again.

**Comment by LautaroL20** [comment]
In order to solve this issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by TeamSpen210** [comment]
This has nothing to do with missing resources, and that should have been fixed ages ago. It depends on what exact items you have in your map, and what orientation.

**Comment by LautaroL20** [comment]
> This has nothing to do with missing resources, and that should have been fixed ages ago.

Nobody has said that this issue has to do with "missing resources"... usually, when people say that they can not even compile an empty chamber, that could be due to many other reasons (one of them could be due that they have installed many mods with stuff that could be interfering in some way) but ultimately, the steps that i give to people who can not compile empty chambers usually fixes these issues in some cases.

By the way, have you never seen how some people with this same issue have said that my steps solved their building errors?

**Comment by LautaroL20** [comment]
Not sure what was going on with this but judging by the time date of the issue, you were using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.
