### ISSUE TITLE
BEE2 4.37.0 error when launching

### ISSUE THREAD

**Issue by ILBenvenuto** [BEEmod/BEE2.4#1415]
When i try to start the exe, a window instantly appear and closes, and then the exe file disappears. I can share the log files if it can be helpful.

[bee2.error.log](https://github.com/BEEmod/BEE2.4/files/5589467/bee2.error.log)
[bee2.log](https://github.com/BEEmod/BEE2.4/files/5589468/bee2.log)

I merged the packages and the win version, so it should work, or i missed something?

PS: I tried with an older version and it worked, but then there was another problem, when i was in game, the game could not "build" the chamber. I could use the editor though.

PS: Ok sorry, the old version now works, it was my game that was corrupt, but the original problem with the 4.37.0 remains.

**Comment by LautaroL20** [comment]
The only thing on those logs that would indicate the cause of the error is `[WARNING] sound.<module>(): ERROR:SOUNDS NOT INITIALISED!`. In the latest BEE2 release, the application will disable the sounds effect instead of crashing, but even if this was not the cause of your issue, I do not think that your issue would happen anymore in version 4.40.2 of BEE2.
