### ISSUE TITLE
Determining the correct PosIsSolid values has become impossible (or extremely difficult) 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1428]
Trying to determine the correct `PosIsSolid` values has become impossible (or extremely difficult), this also occurs with `BlockType`. This is a big problem for the community in the case that they wanted to make items with brushes, and the developer wanted to set up those brushes for when they must or must not be generate through conditions as `PosIsSolid` and `BlockType` as well

Apparently, in Hammer there is a status bar on the right-hand side at the bottom of the window that is supposedly to give the number values for those conditions, but i´ve tested this several times and those values are totally inaccurate for Beemod.

**Suggestion:** implement something in Beemod to allow the people to debug this problem in an easy way to find the correct values for the `PosIsSolid` and `BlockType` conditions.

**Comment by Luke18033** [comment]
Can you please stop pinning issues just because *you* think they're important? Generally, an issue should only be pinned if either:
- It's frequently duplicated or otherwise brought up often (logic gate compile error, Mac crashes)
- It's a larger project that will be worked on over time (the tiling system, reimplementing BEE2.2 items)

This definitely isn't a long-term project (it would just require some adjustments to those conditions) and I haven't seen anyone else complain about this before, so I really don't think it should be pinned. I had this same problem back with BEEmod/BEE2-items#3356 - you say it's important, "serious enough to deserve to be pinned"...so then why hasn't anyone else brought it up before or since then?

So I'm going to unpin this for now. If custom package creators start complaining about this as well, or the issue gets duplicated a lot, then I'll re-pin it.
