### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: \\AppData\\Roaming\\BEEMOD2\\screenshot.jpg'

### ISSUE THREAD

**Issue by wjrowan** [BEEmod/BEE2.4#1429]
Every Time I try to export my custom pallets I get this error message, Please help:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 881, in export_editoritems
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 74, in write_settings
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 34, in get_curr_settings
  File "F:\Git\BEE2.4\src\CompilerPane.py", line 180, in save_load_compile_pane
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\willi\\AppData\\Roaming\\BEEMOD2\\screenshot.jpg'

I have the latest version of bee2.4 and the packages and I had beemod1.5 beforehand.

**Comment by seagemgames** [comment]
it seems you either set your Portal 2 location to there, or it's missing that file. Try reinstalling?

**Comment by wjrowan** [comment]
Try reinstalling what beemod or portal 2

**Comment by wjrowan** [comment]
This is also my editor menu now if this helps
![image](https://user-images.githubusercontent.com/54865890/101462500-0361ab00-3988-11eb-8035-d9c04a5ae55f.png)

**Comment by LautaroL20** [comment]
> wjrowan said: "This is also my editor menu now if this helps"
> ![image](https://user-images.githubusercontent.com/54865890/101462500-0361ab00-3988-11eb-8035-d9c04a5ae55f.png)

That is not normal at all... in order to solve that missing textures/models issue, you will have to do the following:

1. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

2. Wait 1 minute while BEEmod resources are removed from Portal 2.

3. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

4. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).

5. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

6. Select a palette and style, and export it to the game as normal.

7. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by wjrowan** [comment]
Ok I did the first part of what you said and will commence onto the second half it said one file was broken

**Comment by wjrowan** [comment]
For some reason when i uninstall Bee2 it gives me this error
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\gameMan.py", line 1542, in remove_game
  File "F:\Git\BEE2.4\src\UI.py", line 442, in quit_application
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 74, in write_settings
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 34, in get_curr_settings
  File "F:\Git\BEE2.4\src\CompilerPane.py", line 180, in save_load_compile_pane
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\willi\\AppData\\Roaming\\BEEMOD2\\screenshot.jpg'
but it does work

**Comment by wjrowan** [comment]
IT WORKED THANK YOU!!!

**Comment by LautaroL20** [comment]
No problem.
