### ISSUE TITLE
Whenever I try to publish a map in portal 2 with beemod 2.4 it says: 'there was an error building the puzzle'.

### ISSUE THREAD

**Issue by Floopus** [BEEmod/BEE2.4#1433]
it comes up with this error message in the console:

VVIS failed.

Valve Software - vvis.exe (Nov 12 2019)
12 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1608032396.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1608032396.prt
LoadPortals: couldn't read c:\program f

**Comment by seagemgames** [comment]
That, my friend will be a leak. Could you send these files?
c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1608032396.bsp
c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1608032396.prt

Also, what version of BEEmod (4.36.1, 4.37.0 etc), and are you using any UCPs?

**Comment by Floopus** [comment]
I am using bee 2.4 but I am not very good with files. In total, out of the three maps I have made, only one actually works. The other two have the same error. It is only when I publish the map this error happens, rebuilding is fine.

**Comment by LautaroL20** [comment]
Probably, you do not have that map with the leak anymore, otherwise we could have given it a check on Hammer to determine the origin of the leak. In any case, make sure to get the latest application and packages version of BEE2 and if this problem persists for you, let us know and we will re-open the issue.
