### ISSUE TITLE
Error with beemod: "ValueError: Bad EmbeddedVoxel data in item ITEM_BEE2_NEUROTOXIN_VENT!"

### ISSUE THREAD

**Issue by 102182123** [BEEmod/BEE2.4#1438]
![image](https://user-images.githubusercontent.com/61122724/102501906-a0a69880-4086-11eb-9c27-286573a2f81c.png)
What i need to do?

**Comment by LautaroL20** [comment]
According to the image error you have posted, the issue you were having is most likely fixed in the latest BEE2 release as I did not see anyone having problems while trying to export the Neurotoxin item to the game. So, please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open it.
