### ISSUE TITLE
How to install Dev version?

### ISSUE THREAD

**Issue by BigUpBoris2024** [BEEmod/BEE2.4#1439]
I've been trying to install the dev version for a couple of days now, since it has the fix for an issue ive been having. Ive tried using Github desktop to merge them like with packages. No luck. Ive tried using Git CMD to install it, before it says I dont have write permissions while I'm using the hidden admin account. I'm stuck.

**Comment by Notsoartificialintelligence** [comment]
There needs to be an option to install the dev version easily from the main BEE2 page.

**Comment by Notsoartificialintelligence** [comment]
honestly i'm so confused about how you get the dev version

**Comment by Konclan** [comment]
The dev version isn't built. You'd need all the required modules to compile the program. There used to be a tutorial on this but I think its vanished since it was outdated. If you have more questions like this you should ask in the [discord](https://discord.com/invite/hnGFJrz) instead of opening an issue.

**Comment by BigUpBoris2024** [comment]
after another day, cant figure it out, so ill just wait for the next release with the fix
