### ISSUE TITLE
3 issues I've noticed

### ISSUE THREAD

**Issue by TimmyBuildar** [BEEmod/BEE2.4#1522]
1. Autoportals do not function at all, even when set to Start Enabled.

2. Lights do not appear correctly in styles other than clean. Essentially, I first noticed in P1 style that the light strips were appearing instead of the light holes, but the light strips were z-fighting with the wall. I then investigated other styles and found that none of the light props were appearing in Old Aperture and were replaced with the z-fighting light strips, witch were behind the wood boards, with the exception of 1980s.

3. BTS simply does not compile.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Comment by seagemgames** [comment]
You've also posted on the wrong repo, this should be in [BEE2-items](https://github.com/BEEmod/BEE2-items).
Next time, read the [Contributing Guidelines](https://github.com/BEEmod/.github/blob/master/contributing.md) and the [FAQ](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md)

**Comment by TimmyBuildar** [comment]
ah thanks, I'll do that next time

**Comment by LautaroL20** [comment]
> I'll do that next time

Remember that your issue has been closed due to the reasons given above, so if you want to create your issue reports in the items repro, go ahead.
