### ISSUE TITLE
Virus found in Ver. Version 4.39.2

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#1537]
"Antivir" block. My Antivirus Program has found 2 Virus in the 64 Bit and 3 Virus in the 32 Bit Version 4.39.2 :-(
Please show what the Problem is. Thx.

**Comment by dunkler-schatten** [comment]
![Beemod](https://user-images.githubusercontent.com/18405990/110465742-1e51d180-80d5-11eb-808e-4eeee2db5221.jpg)
Virus in the 64 Bit Version 4.39.2

**Comment by LautaroL20** [comment]
That is a false positive, in order to make BEE2 work well, you will have to make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

**Comment by dunkler-schatten** [comment]
mmhmm ok thanks for Answer.

**Comment by LautaroL20** [comment]
If you do not trust BEE2, just do not install it but I can guarantee you that it is secure.
