### ISSUE TITLE
[pedantic as hell] BEEMOD writes VDF files with slightly incorrect indentation

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2.4#1548]
**BEE2 version:** 4.38.1

I'm writing a VDF serializer in Rust, and while looking for source files to glean the format from I noticed a discrepancy between BEE's `editoritems.txt` and `editoritems_original.txt.` BEE seems to increase the indentation level before writing the opening `{` and decrease it after writing the `}`. Both of these are reversed from the way Valve does it.

`editoritems_original.txt` starts like this. Notice how the `{` matches the indentation level of the key preceding it, and is one level shallower than the keys inside the block.
```
"ItemData"
{
	"Item"
	{
		"ItemClass"		"ItemPedestalButton"
		"Type"			"ITEM_BUTTON_PEDESTAL"
		"Editor"
		{
			"SubType"
			{
				"Name"		"PORTAL2_PuzzleEditor_Item_pedestal_button"
				"Model"
				{
					"ModelName"		"switch.3ds"
					"TextureName"	"buttonpedestal.png"
				}
```

The BEE-generated `editoritems.txt` starts like this. Notice how the `{` is one level deeper than the key preceding it, and is at the same level as the keys inside the block. In my opinion, this is a lot harder to read than Valve's file.
```
"ItemData"
	{
	"Item"
		{
		"Type" "ITEM_POINT_LIGHT"
		"Exporting"
			{
			"Instances"
				{
				"0"
					{
					"Name" "instances/BEE2/clean/point_light.vmf"
					"EntityCount" "0"
					}
				}
			"TargetName" "plight"
			"Offset" "64 64 64"
			}
```

You can also see how bee-generated editoritems files end with an indented `}`, but Valve's just end with a `}` on its own line.

**Comment by Luke18033** [comment]
TeamSpen does it this way, it's always kinda bugged me...but it's still valid syntax, I don't think it's worth it to go through every config file in every package just to change the indentation.

**Comment by TeamSpen210** [comment]
Yep, this is intentional on my part, it's my preferred indentation style. I like it because (with long key names) makes the brace "connect" to the line above and below it. It's entirely an aesthetic preference. For your serializer, one thing to be aware of is that you need to have an option to decide whether to parse `\` escapes or not. In code that's only enabled for certain files. Another unorthodox thing is that this is valid for a multi-line value:
```c
"block"
    {
    "key" "value"
    "key" "multi
line value with, note indentation"
    "key" another"
    }
```
Finally you'll want to handle bare strings - any characters other than whitespace or the various operators should be implicitly treated as a key. For reference, this is my main parse testing [sample](https://github.com/TeamSpen210/srctools/blob/2826b3ae2d0b0979d0b82470e5dac99b22958bb4/srctools/test/test_property_parser.py#L86-L201).
