### ISSUE TITLE
 another bugs in 4.39.2

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2.4#1570]
1.conveyor belt crush textures of water and crush the sound if surroundings
2.portal gun stand cannot be spinning. if you connect,=issue=error building
3.autoportals dont open
4.catwalk will crush the game if try to pull surface under it
5.button cube has no texture in overgrown style

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

Also, you have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
