### ISSUE TITLE
Uncaught "ValueError: Invalid component name '-b'!" on Start-Up on Ubuntu 20.10

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2.4#1585]
**BEE2 version:** 4.39.2

**Description of the bug:** The application crashes on start-up with the following error-message:

```
[I] utils.setup_localisations(): Language: 'en_GB'
[I] BEE2_launch.<module>(): Arguments: ['/home/userzeroex/beemod/BEE2.4/dist/64bit/BEE2/BEE2', '-B', '-S', '-E', '-s', '-c', 'from multiprocessing.resource_tracker import main;main(9)']
[I] BEE2_launch.<module>(): Running "-b", version 4.39.2:
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 57, in <module>
ValueError: Invalid component name "-b"!
```

**Steps to reproduce:**

1. Follow the build-instructions
2. Start BEEMod

**Additional information:**

* OS: Ubuntu 20.10 Groovy Gorilla on x86_64
* Python: CPython v. 3.8.6-final
* [Generated log-file](https://github.com/BEEmod/BEE2.4/files/6460639/bee2.log)

**Comment by userzeroex** [comment]
I decided to try to run `src/BEE2_launch.pyw` directly using my system's Python-installation (CPython 3.8.6) instead of packaging the app with PyInstaller. I still encountered a fatal error ([log-file](https://github.com/BEEmod/BEE2.4/files/6467106/bee2.log)), but the app at least started and prompted me to enter *Portal 2*'s game-directory.

From that log-file, you can see that no arguments were passed along, except for the filename of the executed file (as expected):

```
[INFO] BEE2_launch.<module>(): Arguments: ['BEE2_launch.pyw']
```

All of the extra arguments appended to `sys.argv` (`-B`, `-c` , `-E`, `-s`, and `-S`) are valid arguments to CPython ([see here](https://docs.python.org/3.8/using/cmdline.html#command-line-and-environment)) and they seem to isolate the Python-environment (by ignoring Python-related environment-variables, disabling `site-packages/` being added to `sys.path`, and so on). I suspect PyInstaller may be adding them as part of packaging the app, but I'm not that familiar with PyInstaller so I can't say for sure.

**Comment by TeamSpen210** [comment]
Ahh, it might be the multiprocessing process. Try removing these lines: https://github.com/BEEmod/BEE2.4/blob/eba16f1f62ee57534c399b225116a1cdd5c798e7/src/BEE2_launch.pyw#L19-L20

**Comment by userzeroex** [comment]
Unfortunately, commenting out the two highlighted lines sort of worked. Invoking `BEE2_launch.pyw` directly or running BEE2 after PyInstaller has packaged it doesn't even start the app and instead crashes with the following messages:

```
[I] utils.setup_localisations(): Language: 'en_GB'
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version 4.39.2:
[W] img.png(): ERROR: "images/bee2/error.png" does not exist!
[W] img.png(): ERROR: "images/bee2/splash_logo.png" does not exist!
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 177 requests (177 known processed) with 2 events remaining.
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 1046 requests (1046 known processed) with 0 events remaining.
```

The above is after running the PyInstaller-packaged BEE2 app; when invoking `BEE2_launch.pyw` directly, the argument is `'BEE2_launch.pyw'`. Notably, however, no extra arguments seem to have been passed in when running the packaged app, so @TeamSpen210 did work in that regard. Though the app is not running, it solves the problem this issue addressed so I suppose it can be closed now.

**Comment by TeamSpen210** [comment]
Seems like it's not finding the correct path for the images folder, then crashing when setting the app icon. After this block, you might want to print out `_INSTALL_ROOT`, see where it thinks the app folder is:
https://github.com/BEEmod/BEE2.4/blob/eba16f1f62ee57534c399b225116a1cdd5c798e7/src/utils.py#L85-L91

**Comment by userzeroex** [comment]
When invoking with `python3`: `/home/userzeroex/beemod/BEE2.4` (i.e. the "root" folder which contains `src/`; `src/` was also the working directory)
When running the packaged app: `/home/userzeroex/beemod/BEE2.4/dist/64bit/BEE2` (again, the folder was also the working directory)

I'd like to highlight these two log-messages:

```
[W] img.png(): ERROR: "images/bee2/error.png" does not exist!
[W] img.png(): ERROR: "images/bee2/splash_logo.png" does not exist!
```

`images/` definitely exists, but `images/bee2/` does not. `images/BEE2` does, however, but since Linux's paths are case-sensitive they're two different places entirely. It makes no difference under Windows since its filesystem is case-insensitive. Sure enough, by renaming `images/BEE2/` to `images/bee2`, the two errors go away:

```
_INSTALL_ROOT: /home/userzeroex/beemod/BEE2.4/dist/64bit/BEE2  # My debug-message.
[I] utils.setup_localisations(): Language: 'en_GB'
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version 4.39.2:
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 177 requests (177 known processed) with 2 events remaining.
X connection to :0 broken (explicit kill or server shutdown).
```

**Comment by TeamSpen210** [comment]
Aha, yeah I don't handle case sensitivity very well.

**Comment by TeamSpen210** [comment]
I suspect the fatal error might be coming from these lines which set the app icon:
https://github.com/BEEmod/BEE2.4/blob/eba16f1f62ee57534c399b225116a1cdd5c798e7/src/app/tk_tools.py#L72-L79
This suggests the icon is too big or something. Try commenting line 79 to turn off the icon-setting, maybe that'll bypass it?

**Comment by userzeroex** [comment]
No, but the app does seem to get further along:

```
[I] utils.setup_localisations(): Language: 'en_GB'
[I] BEE2_launch.<module>(): Arguments: ['../dist/64bit/BEE2/BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version 4.39.2:
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 178 requests (178 known processed) with 2 events remaining.
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 1062 requests (1062 known processed) with 0 events remaining.
```
