### ISSUE TITLE
Creates issues with puzzlemaker_export

### ISSUE THREAD

**Issue by stopmotio** [BEEmod/BEE2.4#1617]
**4.39.1**

**Description of the bug: Several different items do not export properly, because they link to an instance that doesn't exist. Other items, such as vactubes, are not processed correctly and thus are incomplete and broken.**

**Expected behavior: To export like vanilla PTI**

**Steps to reproduce: **

- Create a test chamber with some of the BEEMOD items(slopes, vactubes, windows, almost anything)
- Build to make sure it works normally
- use `puzzlemaker_export` to create a vmf
- open in hammer and compile
- disaster

**Additional information: These errors are fixable by removing all broken instances in Hammer. This may leave the level incomplete.**

**Comment by koerismo** [comment]
Exporting your maps via `puzzlemaker_export` is not only a terrible idea without BEE2.4, but a worse one *with* BEE2.4. This process is incredibly flawed because of the overcomplicated and incredibly optimized nature of BEE2.4-generated levels. If you have your heart set on exporting and REALLY want to edit that puzzlemaker map, just open `sdk_content/maps/styled/preview.vmf` in hammer. No commands necessary.

**Comment by ExoBot343** [comment]
overall, editing peti maps is a bad practice since a lot of the stuff is made with instances and logic that are unintuitive in hammer. not to mention bee2 relies specifically on a special compiler for many items which don't work correctly in hammer. this is covered in the faq as well

**Comment by stopmotio** [comment]
Portal 2 level logic is horrible to work with in Hammer on general! That's why I use PETI.

**Comment by koerismo** [comment]
However complicated you think hammer logic is, PeTI BEE2.4 logic is 10 times worse.

**Comment by stopmotio** [comment]
My bad, should've checked FAQ.
