### ISSUE TITLE
creaton can you update beemod because its broked by new updates

### ISSUE THREAD

**Issue by portalxd5** [BEEmod/BEE2.4#1619]
creator of the beemod please update beemod because valve dedicated to update portal 2 and after the update some object connection,graphic and corrupted map errors appearing please fix that and update beemod and also the beemod mod pack not working anymore please fix too!

**Comment by LautaroL20** [comment]
@portalxd5 - When Portal 2 gets updated, you must always do the the following in order to make Beemod to keep working:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by FrozenDragon0** [comment]
@portalxd5 You need patience. Updating a mod like this is not a easy task.

**Comment by LautaroL20** [comment]
> FrozenDragon0 said: "You need patience. Updating a mod like this is not a simple as it may seem."

No, in this case the Portal 2 update the only thing that did was override the BEEmod compiler files, but it did not break anything of the mod like the last time with fizzlers. So, with the given steps I gave him should be enough to solve his issue.
