### ISSUE TITLE
Some mistakes, requests, bugs, and errors.

### ISSUE THREAD

**Issue by AXEKING** [BEEmod/BEE2.4#163]
- ~~One of the items is labeled 2/4 not 1/2.~~ (Intentional.)
- [ ] When using the old BEE 2 reflection gel, it does nothing but make things orange.
- [ ] Some items from TeamSpen210's addon for BEE 2.2.5 are not in BEE 2.4 (World Portal Doors, Conveyor Belts, Caged Turrets, Large Faith Plate, etc.). The wall feature only seems to be able to select 2 styles instead of 6. 
  Some items from BEE 2.2.5 have been removed, most notably the TNT turret and the Breakable Glass.
  Add color option to allow coloring things like turrets, doors, etc.
  Add photo option, to add photos into maps.
- [ ] Add Fact Core voices.
- ~~Add Adhesion Gel~~ (It won't work anyway.)
- ~~Add another gel that is green.~~ (Why?)
  The Classical song doesn't seem to work in Overgrown.
- ~~Add Portal Stories: Mel songs into Music Selection~~ (I haven't added this since it massively balloons the download size. I might add after figuring out a way to install updates without redownloading everything.)
  Add Entrance Text option
  Add Hover Turret
- [x] Four Fields/Fizzlers have the same selection texture (Like, in the BEE 2.4 selection). It could cause confusion.
- [x] Combine autosave and save categorizes.
- ~~The Chamberlock is already named or probably mistaken. "The Chamberlock is the room at the end of each Test Chamber that contains an elevator leading to the next one." -Portal Wiki~~ (The item forms the corridor between two chambers, it's not the elevator though.)
- ~~Preplaced Items category has nothing in it.~~ (This only appears if you check "Unlock Default Items", it's the exit/entry doors and large observation room).

**Comment by ellingtonvengaboysmuseum** [comment]
@AXEKING 

- teamspen will implement the items like the world portal door eventually, i can't wait for that one myself to create a surface division field based off it

- some things can't be colored, but a coloring option could be added to the vbsp configs through when you create new items

- photo's can be added to maps for previews.

- adhesion gel is impossible to implement into the game now since it's code was completely removed to make way for the reflection gel, trust me i have tried it

- new gels can't be created, the code for them in the game is encrypted and can't be modified

- portal stories mel music may be extracted and released by me as a individual release someday along with mel's turrets as a alternative turret.

- i am working on a chapter title and number item, speaking of which i am going to ask teamspen for some help on this one soon

- the hover turret code was removed too, not possible to implement it

- we need to create custom skins for those fizzlers in the editor

- we might do that

- the chamber lock is a mid test passageway

**Comment by AXEKING** [comment]
@ellingtonvengaboysmuseum 

Okay, I understand what you mean by chamberlock.
You don't have to add a hover turret, a walking turret will also do.
New gels like electric gel have been created. They just take a lot of coding.
I can't wait for teamspen to implement the items.
By photos, I mean adding them inside the actual map. Not the preview.
I don't really know for "we might do that"
Re implementation of both codes could be possible. Tried looking at previous versions of portal 2?
I've done a little searching and came across this video with the models for adhesion gel. Not it splatting but its a good start. https://www.youtube.com/watch?v=-c79gtqGJ3U


Also, the classical song in the overgrown style when in the map says "No". It gets funny the first time, but gets annoying after a while.

**Comment by Sarcastic-Fantastic** [comment]
Just to add onto this, Machiavellian Bach (the classical song) doesn't work in the Behind The Scenes style either. It's just Kleiner saying "Oh fiddlesticks" haha.

**Comment by jccreszMinecraft** [comment]
Older Items from BEEMOD are coming to the new version, but TeamSpen needs
time to port them.

Adhesion Gel is not going to happen because the code for it was removed
from Portal 2. The person in the video is using worldportals and
teleportation.
PS: Mel's Music will be added within the next few releases.

On Mon, Jan 18, 2016 at 8:00 PM, Sarcastic-Fantastic <
notifications@github.com> wrote:

> Just to add onto this, Machiavellian Bach (the classical song) doesn't
> work in the Behind The Scenes style either. It's just Kleiner saying "Oh
> fiddlesticks" haha.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/163#issuecomment-172695462>.
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by Konclan** [comment]
There does need to be some form of Text Trigger...
But I don't see how that could be implemented. Maybe as text box in the exe itself. But If that would change when editing maps it could get annoying when editing between maps.

**Comment by LautaroL20** [comment]
Reflection gel works pretty normal. Some items you mentioned is already going to be implemented. And the breakable glass will surely be implemented in next release. As for the suggestion, you should split them into a separate issue.

**Comment by CockroachSlayer** [comment]
There is a mod that readds the hover turret as it was in the beta. You could _possibly_ get the permission to use it in bee 2?
