### ISSUE TITLE
Windows Defender detected a trojan

### ISSUE THREAD

**Issue by zooz8882** [BEEmod/BEE2.4#1631]
**BEE2 version:** Newest version of Beemod, 4.40.2.

**Description of the bug:** Windows defender (potentially incorrectly) identifies a file as a virus/trojan when launching Bee.

**Steps to reproduce:** This issue has occurred previously with other versions of Bee.  Enabling antivirus software and trying to launch Bee should reproduce the error.

**Additional information:** 
![Viruswarning](https://user-images.githubusercontent.com/52897089/124677668-f578f780-de8e-11eb-8cf9-1ff54b648755.png)
![Virusname](https://user-images.githubusercontent.com/52897089/124677679-f90c7e80-de8e-11eb-8bb7-351b2bb8aa86.png)

Allowing the file to run in Windows Defender does not work as for some reason it removes itself before any action can be taken.  This also removes BEE2.exe.  I have tried adding Portal 2's "bin" folder to the exclusion list but the error persists.

**EDIT:** I have added the folder I keep Beemod in to the exclusion list and it seems to have fixed the problem.  This issue can be closed now.

**Comment by LautaroL20** [comment]
That is a false positive, make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

**Comment by Luke18033** [comment]
It either doesn't like Python, or is just flagging it because it's an uncommon program. Either way it's not something we can really fix.

**Comment by HRudyPlayZ** [comment]
It's a false positive. It's been flagged either because it's  replacing Portal 2's files or because it's not ran by a lot of people (if you have a SmartScreen popup, either disable SmartScreen or allow it in the file properties, it's pretty much useless anyways as it just checks for file age)
The folder you should exclude isn't Portal 2's folder but the folder where you extracted BEEMOD.

**Comment by Dornskiman** [comment]
You guys better be right cuz i don't want a virus on my pc

**Comment by FrozenDragon0** [comment]
> You guys better be right cuz i don't want a virus on my pc

You didn't have to comment on an old post and if BEE2 was actually a virus then none would be using it. False positives do happen and BEE2 occasionally gets flagged as one even though it does no harm at all.

**Comment by Dornskiman** [comment]
it worked so yay thanks
