### ISSUE TITLE
VoiceLines Bug

### ISSUE THREAD

**Issue by CN1o2** [BEEmod/BEE2.4#1654]
I'm looking to put voices on my test cameras. I can even choose the character, however, when I set it up, the executable shows me an error and it crashes.

![Errobeemod2](https://user-images.githubusercontent.com/88097966/127742306-12c13ff0-1d9f-4241-b8a1-b30407713484.png)

**Comment by HeimlichLaboratories** [comment]
By "cameras" you mean "chambers", correct?

**Comment by CN1o2** [comment]
@HeimlichLaboratories Yes

**Comment by LautaroL20** [comment]
That image you have posted is clearly showing that the origin of the cause for this error is exactly the same as: https://github.com/BEEmod/BEE2.4/issues/1624, so your issue is a duplicate. I already told you that you need to play more attention if the issue you are having was already reported by someone else on the BEEmod repositories.

**Comment by CN1o2** [comment]
@LautaroL20 I'm sorry, I promise I'll pay more attention
