### ISSUE TITLE
When starting the program, an error pops up - The program cannot be started, since there is no api-ms-win-core-path-l1-1-0.dll.

### ISSUE THREAD

**Issue by Mitia514** [BEEmod/BEE2.4#1754]
### BEE2 Application Version

BEE2 v4.40.2 win64

### BEE2 Package Version

BEE4.39.1 packages

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
I don't know where to get the log
```

**Comment by Mitia514** [comment]
![2021-11-06_125155](https://user-images.githubusercontent.com/37024972/140605678-8c14a776-4ab3-450e-905f-23fb0c3b36df.jpg)

**Comment by Mitia514** [comment]
then comes this error
![2021-11-06_130018](https://user-images.githubusercontent.com/37024972/140605702-8c82a978-a7b1-4359-a53b-ec2c7a27548a.jpg)

**Comment by LautaroL20** [comment]
That error will only happen if you try to run the 64-bit version of BEEmod on Windows 7/8.1 systems. The 64-bit BEEmod version is for Windows 10, only and the 32-bit BEEmod version is for Windows 7/8.1, regardless if your OS is 32 or 64 bit. Definitelly, I think that when a new BEEmod release is out, the download section instead of say 32-bit version, it should say Windows 7/8.1 BEEmod version, and instead of 64-bit it should say Windows 10 BEEmod version so it will stop people´s confusion.

**Comment by Mitia514** [comment]
Thanks for the info, I thought I had something broken. You reassured me

**Comment by LautaroL20** [comment]
No problem.
