### ISSUE TITLE
Cant compile a puzzle

### ISSUE THREAD

**Issue by hay-dude007** [BEEmod/BEE2.4#1761]
### BEE2 Application Version

4.40.0 32bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (32bit)

### Description of the bug

If I try to "playtest" my level it says in the console:
PORTAL2 PUZZLEMAKER]  Compilation time (after export): 48 (ms)
Could not execute the command:
   "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Windows gave the error message:
   "Das System kann die angegebene Datei nicht finden."

VBSP failed.

Failed to start process ("C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/)

### Expected behavior

I expected that Portal2 would start normally

### Steps to reproduce

Step 1: Try to "playtest" the level.
Step 2: It will say that an error occured while creating the puzzle.

### Logs and Reports

```shell
I refer to to the Description of the Bug
```

### Additional information

pls send help

**Comment by LautaroL20** [comment]
You've made this issue with what can now be considered are outdated versions of the application and packages. In order to solve this issue, make sure to get the latest app and packages version and then make sure to do the following:

1.  Make sure any antivirus software is not blocking the executable of BEEmod (BEE2.exe) and add it in your antivirus exception list. Also, you'll have do the same with the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Not doing this may cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have installed the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by Luke18033** [comment]
You don't need to do all those steps anymore.

**Comment by LautaroL20** [comment]
> Luke18033 said: "You don't need to do all those steps anymore."

Well, it depends on the situation. In case of **step 1** , unless there is someone who do not have installed an antivirus (as is my case), I still see this step useful as it teaches the people on how to prevent any antivirus from obstructing the normal behavior of BEEmod because otherwise it can lend in a compile error, or not being able to launch the app at all because BEE2.exe due that it gets wrongly flagged as a virus.

In case of **step 2** , it is still useful for some people who can need to do a 100% clean install of BEEmod because the compiler files could be messed up throwing a building error for no reason. In case of **step 4** , yes I agree with you because it may no longer be needed because by just doing step 2 would be enough with that.

In case of **step 5**, I think it is still useful to advice people (see comments of #1769) that they needs to make sure to never use different release versions of the Packages and Application because otherwise issues like #1769 can happen.

In case of **step 6**, it depends because if BEEmod now ensures to export full resources when a person export the pallete after having installed a new release, then yes I am agree with you and this step is no longer needed. If this is not the case, then not doing this step may lend in missing in-game palette icons and models (see [#3849](https://github.com/BEEmod/BEE2-items/issues/3849) which is a recent one, and [#2894](https://github.com/BEEmod/BEE2-items/issues/2894)).

In case of 7, 8 and 9, I will not argue in favor or against them because they are not true/essential steps.
