### ISSUE TITLE
Can't start bee2.4: "The program cannot be started because there is no api-ms-win-core-path-I1-1-0.dll"

### ISSUE THREAD

**Issue by starrpark** [BEEmod/BEE2.4#1767]
### BEE2 Application Version

4.40.2 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
BEE2.exe - System error

The program cannot be started because there is no
api-ms-win-core-path-I1-1-0.dll . Try reinstalling
the program.
text translated from russian
```

### Additional information

![image translated (2)](https://user-images.githubusercontent.com/58990195/141675063-3dd6aada-4be0-42f3-a776-3a0dfd44264d.jpg)
image translated from russian
help me

**Comment by LautaroL20** [comment]
That error will only happen if you try to excecute the 64-bit version of BEEmod on Windows 7/8.1 systems. The 64-bit BEEmod version is for Windows 10, only. The 32-bit BEEmod version is for Windows 7/8.1, regardless if your OS is 32 or 64 bit. Definitelly, I think that when a new BEEmod release is out, the download section instead of say 32-bit version, it should say Windows 7/8.1 BEEmod version, and instead of 64-bit it should say Windows 10 BEEmod version so it will stop people´s confusion.
