### ISSUE TITLE
add BTS style back

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2.4#1788]
### Description of the feature

make a working version of the bts style and add it back to the app

### Why should this be implemented

people enjoy making bts maps but the feature didn't work

**Comment by IggyHopKoopa** [comment]
They're probably not going to add BTS back. You do realize there was a reason that BTS was removed, right? Because the style was substandard and not really possible to function in the puzzlemaker. There's a difference between a puzzlemaker map and a BTS map, that being that test chambers are made up of basic modular and reusable test elements while BTS areas have much more specialized machinery and scenery. The BTS style being applied to a puzzlemaker chamber feels more like a skin being overlayed overtop a normal test chamber, which becomes very apparent the more you observe your sourroundings.

**Comment by Luke18033** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#what-happened-to-bts-style
