### ISSUE TITLE
Mysterious walls in front of the entrance door, completely softlocking the map.

### ISSUE THREAD

**Issue by ToasterCorporation** [BEEmod/BEE2.4#1792]
### BEE2 Application Version

4.41.1

### BEE2 Package Version

2.4.41

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I compile my map sometimes a wall will show up in front of the entrance door, preventing the player from proceeding. Moving items around and recompiling shows the wall moved wherever the door is. From what I've seen once the wall is here the map is completely broken, and you would have to start a new map entirely to get rid of the wall.

### Expected behavior

I expect there to not be any strange walls where there shouldn't be

### Steps to reproduce

It seems completely random, most of the time the map will compile fine and sometimes it will have this wall, once the wall is there however the map is completely broken.

### Additional information

![20220104144157_1](https://user-images.githubusercontent.com/53797687/148115690-d57b0e04-53ea-43a1-8dbb-f03bba09c997.jpg)

**Comment by ToasterCorporation** [comment]
So I moved a bunch of more things around and it eventually compiled correctly so... Guess that's fixed.

**Comment by LautaroL20** [comment]
No, this is something that must be fixed properly, because moving an item from a spot in the puzzlemaker should not be the way to solve issues like this. Can you please replicate this issue again and then post a screenshot from your puzzlemaker showing the items positions so we can also replicate this?

**Comment by ToasterCorporation** [comment]
> No, this is something that must be fixed properly, because moving an item from a spot in the puzzlemaker should not be the way to solve issues like this. Can you please replicate this issue again and then post a screenshot from your puzzlemaker showing the items positions so we can also replicate this?

Replicating it isn't entirely easy as once it starts compiling correctly again, it just doesn't happen again until it decides it wants to. If it happens again I will be sure to say something here again, but with how often I make maps I'm not sure how soon I will see the glitch again.

**Comment by LautaroL20** [comment]
> ToasterCorporation said: "If it happens again I will be sure to say something here again

Well, if it ever happens again, please make sure to take a screenshot from the puzzle editor because this will allow us to see which items and which placements were used so it can help us replicating this issue for a possible fix.

> ToasterCorporation also said: "but with how often I make maps I'm not sure how soon I will see the glitch again."

Well, you do not need to make a serious map for playing it or publish it, it can just be a simple map with the sole purpose of replicating this issue by just using the same items and same placements like the last time you got this issue which was very recent.

**Comment by TeamSpen210** [comment]
In this case it'd probably be necessary to have the p2c or vmf, since it'd depend on the exact coordinates.

**Comment by ToasterCorporation** [comment]
Actually I think I remember what exactly I did to fix it, I didn't realize at the time when I wrote the report that an antline laser was placed behind a wall somehow, when I deleted it is when the world compiled correctly. So this is entirely my fault as far as I know.

**Comment by LautaroL20** [comment]
> ToasterCorporation said: "So this is entirely my fault as far as I know."

It depends on what the situation was, if you placed the Antline Laser inside of a boxel instead of placing it over its surface, then yes because that can break the compiler causing weird issues on the geometry of the map. If you just placed the Antline Laser over the surface of a boxel as usual, then its the Antline Laser´s fault and then the item should be revised for a fix. Do you ever remember if the Antlaser was placed inside or over the surface of a boxel?

**Comment by ToasterCorporation** [comment]
What happened was in the chamber there was an antline laser going underneath some piston platforms, that when I replaced the pistons with normal walls the antline laser was stuck outside of the map itself. That's when the bug happened. When I removed the laser and moved it into the world space, all was fixed.

**Comment by LautaroL20** [comment]
Yep, that's what I suspected, the cause of the weird geometry issue was then that the Antlaser was in the void of the map.

**Comment by sew-ey** [comment]
This is happening to me but I dont have any lasers.
