### ISSUE TITLE
Show compile log in collapsible section of error display window

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1893]
With the implementation of the new compilation error window that is shown in the image of below, now when this window appears, if you then decide to open the game´s console, the log error that should indicate what has failed will not be there, and only irrelevant things will appear instead. If this is intentional, then make the game´s console log error to generate regardless of this new feature because the console´s log is always useful.

![Image](https://user-images.githubusercontent.com/12244376/208021389-46b920cb-9be5-4526-9510-b8d3804807e2.png)

**Comment by Luke18033** [comment]
This is because the compile is technically succeeding as far as the editor is concerned, so it doesn't print the log to the console. You can force it to appear with `developer 1` but that's not ideal, the error display window should probably have a collapsible section added to the bottom that shows the compile log (perhaps with the actual error message highlighted in red?)

**Comment by Luke18033** [comment]
Another sorta dumb idea for this, since a VScript is used to open the error display dialog, you could just write in a bunch of `printl` lines which output the compile log to the console...
