### ISSUE TITLE
Dev: crash opening options menu

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1928]
```
Traceback (most recent call last):
  File "app\optionWindow.py", line 73, in show
  File "app\optionWindow.py", line 314, in load_langs
  File "app\localisation.py", line 199, in get_lang_name
  File "babel\localedata.py", line 140, in load
  File "babel\localedata.py", line 146, in load
ModuleNotFoundError: No module named 'babel.numbers'
```
I have my compile script set up to automatically update modules to the versions specified in `requirements.txt`, so maybe you forgot to bump that to a newer version.

**Comment by TeamSpen210** [comment]
Hmm weird, I do have the exact version mentioned in `requirements.txt`. What I did change is make it a runtime requirement instead of just during freezing the app. That way I could retrieve the language names from the Unicode databases, instead of needing to do that ourselves. Perhaps update `babel` anyway?

**Comment by Luke18033** [comment]
Doesn't seem to have fixed it

**Comment by TeamSpen210** [comment]
Ohh, maybe it's that it's being compiled, and I haven't tried doing that yet? That would explain the missing module.

**Comment by Luke18033** [comment]
Fixed
