### ISSUE TITLE
rocket turrets do not work

### ISSUE THREAD

**Issue by CrashingScience** [BEEmod/BEE2.4#287]
in portal 1 style at least, and the lasers go through walls. The turrets them selves do not appear and cause a leak
![20160415151546_1](https://cloud.githubusercontent.com/assets/16468734/14564465/8e3628aa-031e-11e6-9111-33c832232060.jpg)

**Comment by CUBICinfinity** [comment]
Hmm. I don't know what they are like in the P1 theme, but I tried using one of those turrets in one of my "clean" maps. The behavior I experienced was that it would activate and rise like it should, but then its laser would be fixed in a certain direction (I think straight ahead of itself). The turret's head actually does change direction, locks on where I am and fires a rocket in that direction, but the rocket remains right next to the turret head and eventually explodes. It does hurt me if I get close enough to it.

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1238
