### ISSUE TITLE
Allow entry/exit doors to be on floors/ceilings

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2.4#32]
since choosable entry and exit elevators will be done by style. why not add the extended relaxation vault as a level start type choice with different variants depending on the style. this would be used to introduce you to a story if you created a long series of tests in PTI.
- for 50's underground style, have the ERV be replaced by a train bringing you into aperture (as seen in portal stories mel)
- for overgrown, make it an overgrown relaxation vault with the announcer voice.
- for clean, regular vault with GLaDOS or multiverse cave introducing you.
- for Wheatley, clean but with a Wheatley style test chamber with Wheatley greeting you.

**Comment by TeamSpen210** [comment]
I think this would work better as a standalone item, instead of modifying the regular entrance. That way, the item can be freestanding in the middle of a map, anchored on the floor. What would happen is you unlock the mandatory items, delete the entry and then place the vault item on the floor. It'd have all the logic to ensure you spawn inside nicely. 

In the case of Old Aperture, I think you'd still spawn in the regular enrichment sphere but have a new corridor design, which has an elecator/stairs to raise you up into the map. 

I'll be wanting to make a similar exit door item (which has you drop down into the exit), as well as an upward exit (requiring funnels or a high-speed fling to get to). Perhaps this can be the regular exit door, modified a bit?

**Comment by CrashingScience** [comment]
This souns really cool

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1245
