### ISSUE TITLE
BUG Python not loaded BeeMod pre22

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#397]
Really? 
A new version and BeeMod don't run on Mac. :-(

Error Code:

`/Desktop/BEE2-items-master/bin/BEE2 
dyld: Library not loaded: /opt/local/lib/libintl.8.dylib
  Referenced from: ****/Desktop/BEE2-items-master/bin/BEE2
  Reason: image not found
Trace/BPT trap: 5
`

The Mac has no Directory named "/opt/local/lib/" **/local/lib don't exist.**
i make are directory named local ---> lib and copy the File "libintl.8.dylib" into "/lib"

Error Code in Terminal:

`dyld: Library not loaded: /opt/local/lib/libiconv.2.dylib
  Referenced from: /opt/local/lib/libintl.8.dylib
  Reason: Incompatible library version: libintl.8.dylib requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0
Trace/BPT trap: 5
`

HELP :-(  Please Fix it
Version 21.5 Run Perfect on Mac.

**Comment by TheDarkBomber** [comment]
Get version 8.0.0 or later.

**Comment by dunkler-schatten** [comment]
Who can i get?
Python 8.0.0 or what you mean?
The Latest Python Mac Version is only 3.5.2 ????
https://www.python.org/downloads/release/python-352/

**Comment by TheDarkBomber** [comment]
libint1.8.dylib 8.0.0

**Comment by dunkler-schatten** [comment]
My English is to bad. Don't understand perfect.
The first Problem is. /local/lib don't exists on my mac.
And if not create the folder local and lib in the Folder /opt then have only the Error:

`/Desktop/BEE2-items-master/bin/BEE2 dyld: Library not loaded: /opt/local/lib/libintl.8.dylib Referenced from: ****/Desktop/BEE2-items-master/bin/BEE2 Reason: image not found Trace/BPT trap: 5 `

Ignore my second Error Code in Terminal.
Only that have i found but i can' understand this.
https://trac.macports.org/ticket/31893

Thanks for your help.

**Comment by LautaroL20** [comment]
@dunkler-schatten - Get Pre-release 27 (Packages & Application) since this is most likely fixed now. Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
