### ISSUE TITLE
Style Loading Screens

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#460]
Different styles will use loading screens from the game. It's a small touch but I think it would be neat.

**Comment by LautaroL20** [comment]
Unfortunately, no. Since those loading screens happen before the map is loaded, the game can't read from the map to figure out which one to use. Instead they're determined based on the map name - `sp_a1_` - `sp_a4_` . We can't change the PeTI map name, so this is the one thing that's impossible to do.

**Comment by Konclan** [comment]
Darn, I've seen custom maps use them so I thought there we apart of some configuration.. why does valve have to ruin everything XD

**Comment by Luke18033** [comment]
@LautaroL20 I think TeamSpen210 has said that exact same thing before...did you just copy it?

**Comment by HelloIamapersonthatisalive** [comment]
OH MY GOD YES

**Comment by HelloIamapersonthatisalive** [comment]
oh... so no loading screen

**Comment by peefTube** [comment]
@Luke18033 I think @BenVlodgi was the first to say it WAAAAYYY back when. I used the old BEEMod versions when they still had that new mod smell and I can confirm at least one of the developers for an older BEEMod version said something along the lines of what @LautaroL20 said above.

**Comment by Luke18033** [comment]
No, TeamSpen210 said it in an older issue.
