### ISSUE TITLE
Aperture Tag, Portal Stories Mel, and Portal 1 Songs don't Pack into Maps

### ISSUE THREAD

**Issue by Alfe5** [BEEmod/BEE2.4#473]
I am using pr 23 and the songs render for me but when I post the map and have a friend play it, they can;t hear the music. I own both games and I hear it but no one else can, even if they own the games too. please fix this in a future update.

**Comment by Luke18033** [comment]
Put this on [BEE2-items](https://github.com/BEEmod/BEE2-items).

**Comment by LautaroL20** [comment]
@Luke18033 - Before closing an items issue, move it to the another section like i did last month with tons of them, its not pleasant but worth it.

**Comment by TeamSpen210** [comment]
You can use [this tool](https://github-issue-mover.appspot.com/) to copy issues over - it adds links, and rewrites all the comments.

**Comment by LautaroL20** [comment]
Heh, its funny because l already moved tons of issues a month ago by only using copy paste keys with a considerable ammount of effort, so its a bit late for me. Probably everyone noticed this when you guys saw all the insane ammount of notifications on your inbox about issues moving, even @Luke18033 stop watching both sections after cheked his email inbox, but it was too late LOL!

**Comment by Alfe5** [comment]
i have all the packages
