### ISSUE TITLE
Crsh When Opening Up Editor

### ISSUE THREAD

**Issue by Tiblets** [BEEmod/BEE2.4#501]
After a few day's of beemod it (for some reason) crashes as soon as i select create test chamber

**Comment by matinh0** [comment]
I'm having this problem too

**Comment by LautaroL20** [comment]
@Tiblets @matinh0 - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
