### ISSUE TITLE
BEEMod 2.4.0pr24 Export issues.

### ISSUE THREAD

**Issue by Zealdozer** [BEEmod/BEE2.4#507]
Whenever i try to export my loadout to Portal 2 it will display this message:
"BEE2 - Export Failed!
Copying compiler file python34.dll failed.Ensure the PORTAL 2 is not
running."

Anyone knows what to do? Im clueless :(

**Comment by TheDarkBomber** [comment]
Ensure Portal 2 isn't running.

**Comment by Zealdozer** [comment]
You mean like i have to uninstall? Because at no time is ANY of my steamgames running.

**Comment by laserman120** [comment]
Download a programm that shows you which programm is using the folder and stop it.
Then try it again. If you have something from Intel stop the programm igfxEM.exe with the task Manager and try to export again

**Comment by LautaroL20** [comment]
@Zealdozer - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
