### ISSUE TITLE
my bee2 pallets wont export

### ISSUE THREAD

**Issue by curiositycore** [BEEmod/BEE2.4#510]
when it says exported would you like to open in bee2 and I click yes the pallets are not in the editor

**Comment by Konclan** [comment]
Are you restarting Portal 2 or not?

**Comment by curiositycore** [comment]
No why?

**Comment by TeamSpen210** [comment]
You need to restart for the palette to change.

**Comment by curiositycore** [comment]
I CLOSE PORTAL 2 if that's what you mean

**Comment by curiositycore** [comment]
And open it through the app

**Comment by LautaroL20** [comment]
@curiositycore - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
