### ISSUE TITLE
game crash before main menu's

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2.4#514]
i have found a game crash before the main menu's. I am unable to find the cause because once it happens for the first time the only way to fix it is to reinstall the entire game. validating game cache doesn't do anything... once it happens, it keeps crashing before the main menu comes up after the valve logo appears, removing all bee2 content also doesn't do anything, only fix is to delete all files and reinstall the game and wait hours for it to download.

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
