### ISSUE TITLE
Description window is placed at the bottom can not be moved.

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2.4#518]
Description window is placed at the bottom can not be moved.
![Image](http://csyeah.qiniudn.com/img/QQ%E6%88%AA%E5%9B%BE20170209200012.png)

**Comment by TeamSpen210** [comment]
It should move itself to the top when shown.

**Comment by LautaroL20** [comment]
@goodDOS - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
