### ISSUE TITLE
Item Compression Option

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#529]
Either an option to compress items that have 3 variants down to one icon on the item selection field or have that by default and have an option to show all item variants. This is to help clean up the already over cluttered item menu.

**Comment by Byzarru** [comment]
There's already a suggestion to condense the custom fizzlers. Angled Panels could mesh with Angled Glass and Grating. Lasers could be bundled with HEPs as well as their catchers, and that's all I can think of. I think the problem is that there are too many variables in individual items that their counterpart would need to have those same variables.

**Comment by TeamSpen210** [comment]
No, this is a suggestion to get rid of (weighted, cube, sphere) on the list in the BEE2 app, and just show the grouped item. Merging those other item types isn't actually possible.

**Comment by Byzarru** [comment]
Leave an option in the settings to show full/condensed inventory then?

**Comment by TeamSpen210** [comment]
Indeed.

**Comment by ZipZoptheCat** [comment]
I would definately appreciate more combining of similar items via the cube type button. It often seems there's not enough space to fit all the element into the pallette.

**Comment by TeamSpen210** [comment]
That's a seperate, unrelated issue.
