### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jasonotto** [BEEmod/BEE2.4#556]
![Image](https://cloud.githubusercontent.com/assets/16061683/24074695/d194c482-0c0d-11e7-92eb-97c92f8f9ef3.png)

it worked fine all the time

**Comment by TeamSpen210** [comment]
Delete that config file.

**Comment by LautaroL20** [comment]
@Jasonotto - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
