### ISSUE TITLE
2.4.pr24 50's Style is Broken

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#563]
This started happening today. This computer has given me trouble with modding Starbound before (I ended up having to go into Safe Mode so I could delete the installation directory for that one), and I've done everything I can to try to stop this issue. I'm really eyeing that "WinError 5," there's something really peculiar about that...

![image](https://cloud.githubusercontent.com/assets/26728974/24385324/6ceab2fe-131e-11e7-9c8c-b3f542725c69.png)

**Comment by TeamSpen210** [comment]
You might have a computer issue with permissions - it's erroring when trying to delete/overwrite a fille.

**Comment by peefTube** [comment]
So... How exactly do I correct that? I've got people begging me to make more maps and I can't do so without BEEMod items.

**Comment by peefTube** [comment]
I found something that seems to make some sense out of what's going on. Do you think you could implement this?

http://stackoverflow.com/questions/36360167/when-using-python-os-rmdir-get-permissionerror-winerror-5-access-is-denied

**Comment by peefTube** [comment]
**EUREKA!!!**

I figured out what that annoying "WinError 5" might have been. It seems to be something that annoys quite a few people. To circumvent it all you have to do is press Windows+X, select Command Prompt (Admin), and type in: `net user administrator enable:yes`

However, BEEMod is only getting worse with each fix I use, the list of inaccessible items is bigger and bigger each time...

**Comment by peefTube** [comment]
Somehow, even with the errors, after inputting `net user administrator /active:yes', BEEMod 2 actually exported this time!! It seems that I actually figured it out. Maybe this can help those of you who have this issue....?

**Comment by peefTube** [comment]
I figured out why I'm getting errors now. The 50's style is completely broken, and I can't make ANY chambers in it. I'm using P1 style as of right now but BEEMod still shows the export error:
![image](https://cloud.githubusercontent.com/assets/26728974/25097691/694feea6-235a-11e7-860e-ab5059aeeec4.png)

**Comment by peefTube** [comment]
Also, in Portal 1 style I get #579

**Comment by ZombiePwner1** [comment]
@peefTube This doesn't always happen it's a bug that tends to make that sometimes.

**Comment by peefTube** [comment]
@ZombiePwner1 I tried anything I could to get chambers working with that error popping up, but as soon as I added any items that weren't P2 native, it would completely break.

**Comment by ZombiePwner1** [comment]
@peefTube Strange try asking @TeamSpen210 about it.

**Comment by peefTube** [comment]
> I figured out why I'm getting errors now. The 50's style is completely broken, and I can't make ANY chambers in it. I'm using P1 style as of right now but BEEMod still shows the export error:
![image](https://cloud.githubusercontent.com/assets/26728974/25097691/694feea6-235a-11e7-860e-ab5059aeeec4.png)

What's your take on this @TeamSpen210 ?

**Comment by LautaroL20** [comment]
@peefTube - Get Pre-release 27 (Packages & Application) since this is most likely fixed now. Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
