### ISSUE TITLE
Glass Futbol receivers cause "map coordinates too large" issue

### ISSUE THREAD

**Issue by ApocUni** [BEEmod/BEE2.4#576]
Trying to make a puzzle with the glass futbol when I found out any futbol sockets set to receive a futbol instead of spawning one (auto-drop first cube disabled) cause Portal 2 to refuse to finish compiling the chamber. After I press F9, the three bars that appear before the final loading of the map fill completely and the black loading screen with the Aperture logo and the 15 little dots in the bottom of the right appears, but after two of those dots fill (always exactly two) the screen will turn black and fade into the screen again, however no dots will turn blue (at least in the first fifteen minutes of waiting). In the developer console messages will appear saying a few UGC files didn't load correctly, and the map's coordinates extend too far. Both before and after attempting to compile the puzzle, the single futbol socket set to spawn a futbol (auto-drop first cube enabled) worked fine and no compile issues occurred, and the respawn cube checkbox didn't have an effect either way. However no matter what amount of receiving futbol sockets were in the map (tried every number from one to four), it would not properly compile as the loading screen wouldn't progress past that same point.  There were a few other items in the map that I'm not sure whether or not they contribute to the problem: reversed funnel, pellet launcher and two pellet catchers, small signage set to option 7 (exit door), cold light strips and square cold lights, and a few fizzlers. Not entirely sure why this happens and couldn't find a simple fix...

**Comment by Luke18033** [comment]
Uhm, GitHub really needs to fix that duplicate message, I think it's the other way around.

**Comment by Luke18033** [comment]
I think this would be a BEE2-items issue, although I'm not exactly sure.

**Comment by LautaroL20** [comment]
Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, you will have to do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
