### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2.4#578]
1. Ask for the user's steam name in order to use their screenshots from Portal 2 as BEEmod splash screens
new 2. With the Death Fizzler, make it so that choosing "Fizzler" will deactivate the fizzler and the same for laserfield, rather than using the a/b system

new 3. allow the Trigger autosave to take inputs

**Comment by TheDarkBomber** [comment]
1. Or there could be a feature for BEE2.4 that allows screenshots to be used as a splash screen without embedding it into the application.
2. We already have that. See the Wiki page of this GitHub repository.
3. Already been suggested.

**Comment by iEnderMan06** [comment]
@TheDarkBomber You can easily enough add in the screenshots yourself, However I was wanting a more automatic way of doing it

**Comment by TheDarkBomber** [comment]
No need.

**Comment by Konclan** [comment]
Getting to your screenshot folder is easy.. trying to automate it would be hard and is not necessary

**Comment by Luke18033** [comment]
@iEnderMan06 - Please don't add fake labels like [suggestion] to issues, just wait for somebody to add them.

**Comment by iEnderMan06** [comment]
@Luke18033 Oh, I thought that added them, sorry

**Comment by Luke18033** [comment]
1. I personally dislike how Steam uses your screenshots as the background, since most of mine were either taken accidentally or used for bug reports. I wouldn't want this in BEE2.4.
2. Not a good idea. See [this page](https://github.com/BEEmod/BEE2-items/wiki/Death-Fizzler) for info.
3. I already suggested this in BEEmod/BEE2-items#1077.
