### ISSUE TITLE
BEEMod decided to self-destruct

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#584]
While deleting palettes, BEEMod decided to self-destruct:

![image](https://cloud.githubusercontent.com/assets/26728974/25299587/6d98f3aa-26b5-11e7-918f-c1059d7bd366.png)

@TeamSpen210 
@LautaroL20
Any ideas as to what the heck is going on here?

**Comment by LautaroL20** [comment]
> peefTube said: "BEEMod decided to self-destruct"

No idea why that would happen.

**Comment by TeamSpen210** [comment]
Oh. You somehow deleted all the palettes and broke it. You shouldn't be able to delete the default ones - the greyed out ones.

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol no idea why it would happen. Also get on steam.

**Comment by TeamSpen210** [comment]
Put this back in the folder for the [original](https://github.com/BEEmod/BEE2.4/raw/master/palettes/original.bee2_palette) palette.

**Comment by peefTube** [comment]
I deleted the custom ones only :/

**Comment by peefTube** [comment]
And it's still broken, even after doing what you said.

**Comment by LautaroL20** [comment]
@peefTube - Get Pre-release 27 (Packages & Application) since this is most likely fixed now. Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
