### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2.4#592]
It keeps on skipping the LAST two steps & makes it so some of my puzzles are glitched or will not upload until I remove a item that is fine. Please help! It is messing with the 1980's by making the Portal Device Begin Dual Until I'm In the chamber, maybe causing the glitch. Please help!!!
-ZFM2004
P.S.:
The fire I meant was the fire when you are at the portal chamber 19's "end" (song during it is 4000 degrees Kelvin)

**Comment by LautaroL20** [comment]
@ZFM2004 - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
