### ISSUE TITLE
Goo bug, panel error and a question

### ISSUE THREAD

**Issue by Te4mLuna** [BEEmod/BEE2.4#652]
Hello, I am using the BEE2.4 Pre release 25 and Item packages currently.
I have stumbled across the following issue.
Using the Overgrown style and editing my maps ingame the goo pits sometimes get a graphical issue.
When actually playing the map you can no only see through the world (whatever is below it for example) and by looking at it it turns birght white. After first encounter with this issue I have only been able to get rid of it by using another style or reinstalling Portal 2 and the mod. I can upload pictures if required.
Secondly, I am not sure if this issue has been stated before but the glass panel in the overgrown style shows up as an error ingame for people playing the map besides me.
To get to my question, is it possible to implement items of the Bee2 mod in Bee2.4 (I remember for example a big light source in form of sun cracking through the roof in the overgrown style for example) ? If so, how ? 
Thank you for any help in advance!

**Comment by Luke18033** [comment]
Overgrown Style fixed that issue long ago, I don't know why it would still be happening. The glass panel error has already been reported I think. The BEE2.2 items are in the process of being reimplemented, see BEEmod/BEE2-items#95.

**Comment by ZombiePwner1** [comment]
Goo that turns completely white is caused by a leak in the map somewhere.

**Comment by Te4mLuna** [comment]
About the goo, I wouldnt report this issue if it was only my pc where it happened. I have the same version of the mod and itemspack on a friends laptop and got the exact same issue unfortunately. About another thing I encountered, I rarely get an issue where the editor is building the map again successfully but when you actually load into it (standard loading screen) it won't do anything and you get stuck on the loading screen. After a while you will be sent back to the main menu and it say you have been disconnected from the servers or something along those lines. If uploading the map on that state to the workshop will corrupt the file that by loading into it you are immediately sent back to main menu but all the options are missing forcing you to restart the game. I have yet only encountered this on the laptop.

**Comment by Te4mLuna** [comment]
oh and also about the goo again: If you take the same map in the editor with the overgrown style, save the map, restart portal 2 choosing the clean style in bee it fixes itself. Normal goo again. Same map.

**Comment by LautaroL20** [comment]
@Te4mLuna - Get the Pre-release 27 (Packages & Application), since this will most likely be fixed, however, once you installed the latest version it is very important you follow the steps from below:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
