### ISSUE TITLE
Bugs on 1980's style

### ISSUE THREAD

**Issue by sloga17** [BEEmod/BEE2.4#663]
Entrance door doesn't open, laser field doesn't render (lasers are invisible), and gel dispenser doesn't work when connected to button (possibly bugged on all styles)

**Comment by LautaroL20** [comment]
I will give it a check at these issues, and ill be posting them in the items-section.

**Comment by LautaroL20** [comment]
@sloga17 - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however once you installed the latest version, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
