### ISSUE TITLE
Make a styleVar so the X sign appears if there is at least one connection.

### ISSUE THREAD

**Issue by QuantiX999** [BEEmod/BEE2.4#668]

**Comment by TeamSpen210** [comment]
I'm not sure how this'd work as a stylevar, since that'd mean all the items in the map would get checkmarks. But I can't influence how the editor decides to place those. It's potentially possible to reconstruct where those would have gone, but it's difficult especially since the antline routing might have to completely change to get it to fit.

**Comment by CreepiX987** [comment]
@TeamSpen210 well, the exit door does that, then why not other items?

**Comment by Luke18033** [comment]
The exit door is hard-coded to do that, we can't make it apply to other items. Additionally as @TeamSpen210 said, it doesn't make sense to have indicator signs on everything. I think somebody once suggested a manually-placeable indicator sign, and also you can connect a NOT gate with Connection Visibility set to none, which will cause the sign to appear.
