### ISSUE TITLE
Singleplayer Overgrown not playable

### ISSUE THREAD

**Issue by pnpBrumi** [BEEmod/BEE2.4#686]
I'm trying to use the the Overgrown stlye with PR26: I set the style to Overgrown, and set music, voice, etc. to the suggested values. I used the first option for both the entrance and the exit corridors, but I get the same problem with basically any corridor. I've only tried the test chamber using the in-game preview, so I didn't actually export the test chamber to the workshop. I used Full lighting.

On entrance, I see this: 
![20170716184640_1](https://user-images.githubusercontent.com/3792978/28249557-559dbeca-6a58-11e7-91d9-fc6604b953d5.jpg)
I can pass through that door, but still it's quite a visual bug.

The exit looks like this:
![20170716184705_1](https://user-images.githubusercontent.com/3792978/28249573-9971c682-6a58-11e7-83d4-b87db1f6c9b0.jpg)
The doorframe looks misplaced, and because of this, I cannot actually exit the chamber.
![20170716184725_1](https://user-images.githubusercontent.com/3792978/28249575-aab12bc2-6a58-11e7-97c4-c2d553802757.jpg)

The chamber is basically the blank just-started-the-editor one, I only placed the exit door a bit higher and added a hard-light bridge to make it accessible.

**Comment by ZombiePwner1** [comment]
@pnpBrumi This is caused by a leak somewhere causing the world portals to go nuts. However i can't seem to think on what is causing it.

**Comment by LautaroL20** [comment]
I might know what is causing you from getting those weird issues, and it is when you were using past Bee2´s releases, those resouces are still in the Portal 2 sub-folders, and since the latest PRL26 does not have the ability to overwritte old resources anymore, the app its now using them. 

The solution to this annoyance:  

You will have to manually delete the following folders from Portal 2: bee2 (located at "Portal 2\sdk_content\maps\instances"), bin and bee2 (located in the main Portal 2 folder). After this, launch Bee PRL26 and make it to export the full resources. Now you should not get those weird issues anymore.

If this did not work, let me know and ill re-open this post.

**Comment by pnpBrumi** [comment]
@LautaroL20 You got it right, thanks! I indeed used a previous version of BEE2 at some time in the past. Had to verify the game cache now and reinstall BEE2, but it works right now.

The only issue I have now is a missing texture (Overgrown, both at the entrance and the exit)
![20170717190814_1](https://user-images.githubusercontent.com/3792978/28281366-1963071a-6b27-11e7-8614-9705f03be923.jpg)

If this is an actual issue and not a simple error on my part, I can open this as a separate issue.

**Comment by LautaroL20** [comment]
@pnpBrumi - That happens due that the PRL25´s Packages got mixed up with a few old resources from older releases. So, some really old bugs that were fixed a long time ago has appeared on the latest public release. Hope this doesn´t occur again with the PRL26´s packages.

Your issue about that missing texture, is already opened: https://github.com/BEEmod/BEE2-items/issues/1938
