### ISSUE TITLE
Cannot startup

### ISSUE THREAD

**Issue by Kotklopot** [BEEmod/BEE2.4#696]
https://gyazo.com/0b5230feacfb451a753a8110d9ca3b3e

This shows up after starting up BEE2.exe.

**Comment by LautaroL20** [comment]
@Kotklopot - Which pre-release are you using? Make sure you have the same version of the packages as well as the app version.

**Comment by Kotklopot** [comment]
Checked that alerady, doesn't work with the latest and older one.

**Comment by LautaroL20** [comment]
Which operative system are you using?

**Comment by LautaroL20** [comment]
As usual with these issues, no response from the author, ill close this until we get a responce.

**Comment by TeamSpen210** [comment]
It's windows from the screenshot.

**Comment by TeamSpen210** [comment]
Download PR24 or 25, it should have _socket.pyc in the bin/ folder. Copy that over and it'll fix the problem.

**Comment by LautaroL20** [comment]
@Kotklopot - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
