### ISSUE TITLE
Monitors break co-op 

### ISSUE THREAD

**Issue by Wklaver** [BEEmod/BEE2.4#703]
if i place a monitor in a co-op map, the map crashes during loading.

**Comment by LautaroL20** [comment]
Which Pre-release version are you using?

**Comment by Wklaver** [comment]
the most resent, 2.6. it allso happend in 2.5

**Comment by LautaroL20** [comment]
@Wklaver - Get Pre-Release 27, this is most likely fixed now, however once you installed the latest version, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by TeamSpen210** [comment]
I'm not sure, but perhaps monitors are not usable in Coop mode - I haven't checked.
