### ISSUE TITLE
Custom Thumbnail doesn't work

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#707]
_From @TREVTRPD on August 6, 2017 15:44_

_Copied from original issue: BEEmod/BEE2-items#2131_

**Comment by Luke18033** [comment]
How exactly does it "not work"?

**Comment by Luke18033** [comment]
_From @TREVTRPD on August 6, 2017 15:46_

When publishing a map, it publishes the peti screenshot

**Comment by Luke18033** [comment]
Do Auto screenshots work, or is that broken as well?

**Comment by TREVTRPD** [comment]
Auto screenshots work

**Comment by LautaroL20** [comment]
@TREVTRPD - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
