### ISSUE TITLE
Having some problems

### ISSUE THREAD

**Issue by yeswellwhatever** [BEEmod/BEE2.4#715]
When I try exporting, I get this message;

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 852, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 658, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 416, in refresh_cache
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\os.py", line 220, in makedirs
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\drawbridge'

I don't have a file on my computer called "Users\Spencer Brown". What's going on?

**Comment by TeamSpen210** [comment]
The `File "xxx" line xx, in xx` lines are a 'traceback', listing basically the path the code took to get to the error - it's very helpful for me to know what exactly was happening when it crashed. Those file paths are the locations the files were on my hard drive when I built the release. The last line is most useful to you though - it indicates for whatever reason BEE2 wasn't given permissions to access the folders.

**Comment by TeamSpen210** [comment]
One thing that can help is installing Portal 2 in a folder outside 'Program Files` - Window's security settings prevent many apps from directly editing that.

**Comment by LautaroL20** [comment]
@yeswellwhatever - I would suggest to search how to get full permissions on Windows 7-10, since nobody is experiencing this issue. Once you do that, do the following:

Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
