### ISSUE TITLE
Doesn't let me rebuild ingame

### ISSUE THREAD

**Issue by TheCourierSix** [BEEmod/BEE2.4#718]
Whenever I use this mod, Its never lets me rebuild to test my edits. Please fix, as everytime I have to verify my game's files to be able to continue.

**Comment by TheCourierSix** [comment]
At this point, I literally cannot rebuild. no matter what i do, it never works. The error I get in the console is this:
[ERROR] vbsp.run_vbsp(): VBSP Failed! (1)

**Comment by ncrecc** [comment]
Post the entire log

**Comment by TheCourierSix** [comment]
Entire log? where do I get that from?
lol sorry n00b

**Comment by TheCourierSix** [comment]
[portal2error.zip](https://github.com/BEEmod/BEE2.4/files/1254109/portal2error.zip)
iz it this?

**Comment by TheCourierSix** [comment]
or this?
[portal2error.txt](https://github.com/BEEmod/BEE2.4/files/1254110/portal2error.txt)

**Comment by ncrecc** [comment]
portal2error.txt probably

**Comment by CyberSquime** [comment]
If you have any triggers in your map, what are they connected to?

**Comment by TheCourierSix** [comment]
Lots of the panels that fold out of the wall.

**Comment by CyberSquime** [comment]
Hm. What other elements are in the map?

**Comment by TheCourierSix** [comment]
see for yourself:
![20170826210548_1](https://user-images.githubusercontent.com/31378587/29747075-7156b670-8aa2-11e7-9ff0-681b50490247.jpg)

![20170826210538_1](https://user-images.githubusercontent.com/31378587/29747076-7157dfc8-8aa2-11e7-8f7e-c0ed34797fd9.jpg)
![20170826210542_1](https://user-images.githubusercontent.com/31378587/29747077-7159074a-8aa2-11e7-926b-a0c14c2d9a94.jpg)

**Comment by CyberSquime** [comment]
Make sure all of the triggers are connected to something. If they are, trying doing a full re-export by going into the BEE application, removing Portal 2 from the game list, re-adding it, and then exporting again. If compiling doesn't work then, i'm stumped.

**Comment by LautaroL20** [comment]
Oh well, from now i will going to save what im gonna to say next, into a .txt file, so i can copy paste it anytime for these kind of sporadic issues: This clearly seems to be an issue caused by the game by using old resources from past Beemod pre-releases, to solving this annoyance, you will have to do the following:

1. Delete the following folders form the Portal 2 directory: bee2, bin, portal2_dlc3, and the "bee2" that is located at `Portal 2\sdk_content\maps\instances`

2. Verify the Game Cache Files. 

3. Make sure to have downloaded and installed the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur.

4. Open Beemod and click on File ----> Options ----> Developmen, and now uncheck the option "Preserve Game Directories".

5. Now choose your favorite Items & Style, and export your palette to the game.

6. Happy mapmaking!
