### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by TheCourierSix** [BEEmod/BEE2.4#721]
I had another page open, but it was closed because someone thought it was solved. My problem is that some things show up as errors, don't show up at all, or just don't work for my friends when they download the maps. I tried the solution that a guy told me, the same guy who closed the post, and it did fix the other issue I had, but not this one. Please help!

**Comment by LautaroL20** [comment]
You said "it did fix the other issue", ok what is the isse you are having now? Can you provide a screenshot at least?

**Comment by Luke18033** [comment]
Probably #720

**Comment by LautaroL20** [comment]
This issue is insubstantial, which pre-release version are you using? Also, after you did my instructions and do a fresh workshop publish, do your friends still experience the samme issue?

**Comment by TheCourierSix** [comment]
No, I never said it worked after that. The issue is just that things added in the mod don't work for other people.  I don't get the point of the mod if they don't.

**Comment by TheCourierSix** [comment]
![20170827124546_1 - copy](https://user-images.githubusercontent.com/31378587/29753476-309827ec-8b27-11e7-962b-365acfa515c6.jpg)
![capture](https://user-images.githubusercontent.com/31378587/29753477-30a4ba66-8b27-11e7-8f3e-d1e54d631c6c.PNG)
![20170827124546_1](https://user-images.githubusercontent.com/31378587/29753478-30a4c3c6-8b27-11e7-99e3-65bf127940f3.jpg)
![20170827124356_1](https://user-images.githubusercontent.com/31378587/29753479-30a73af2-8b27-11e7-9d0e-41e6c4cff76a.jpg)

**Comment by TheCourierSix** [comment]
It fixed the other issue that had to do with no being able to rebuild.

**Comment by LautaroL20** [comment]
Which pre-release version are you using?

**Comment by TeamSpen210** [comment]
I can't really tell what's wrong with your first/third screenshot.

**Comment by LautaroL20** [comment]
Me neither, i don´t see anything wrong on those. The others seems to be a model not getting packed in the map.

**Comment by TheCourierSix** [comment]
It's a problem because I want something to be themed maybe like old aperture, and it's not.

I'm running pr25.

**Comment by TeamSpen210** [comment]
Well, you'll need to set Old Aperture style for that.

**Comment by TheCourierSix** [comment]
It was just an example. Even here, my friends would just see the default editor texture and not overgrown.

**Comment by TeamSpen210** [comment]
That doesn't seem possible. Unless something is extremely wrong. But deleting `bin/` and verifying cache should fix that.

**Comment by TheCourierSix** [comment]
Bin? In Portal 2?

**Comment by LautaroL20** [comment]
![GIF](https://user-images.githubusercontent.com/12244376/29797965-818e2868-8c30-11e7-8197-f9c70c7122ce.gif)

**Comment by LautaroL20** [comment]
@TheCourierSix - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
