### ISSUE TITLE
Holes in the wall and ceiling in overgrown style

### ISSUE THREAD

**Issue by EwokPilot** [BEEmod/BEE2.4#744]
You should add an item that adds holes in the the panels when added. (BTS areas in clean style, Debris and sky outside the roof in overgrown style, and show the sphere in 50's, 60's, 70's, and 80's style) this would make the environments a lot more varied if you allowed map makers to insert these. Also maybe add debris piles as and item that can be inserted into chambers.

**Comment by peefTube** [comment]
I've wanted this idea as well but I also have the understanding that the developers are limited with what the Portal 2 in-game mapping tools are capable of as well as the limitations presented by Portal 2's code. I'd actually recommend using Hammer to make the full map inside the sphere the hard way for the 50's-80's and to also make direct, below-the-surface chambers for Overgrown. Clean style? Same thing. Just use the pre-existing models and such to detail the map yourself.

I know this process is difficult and perhaps somewhat unwieldy but until you get a concrete response as to whether this is a viable addition, I'd recommend learning the harder, more complicated tool, especially since once you understand the more complicated tool, you can create **much, much more** with the tools available, such as designing structures that'd be just plain impossible to build in the PeTI.

(meanwhile I'm being hypocritical since I've never really taken the time to learn Hammer lol)

**Comment by ZombiePwner1** [comment]
@EwokPilot  @peefTube It is possible to make this but it will be very complex. As a matter of fact there is 2 ways we can do this. We can either make an item that puts holes in the walls in ceiling or we can do the hard way which is the compiler.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

**Comment by TeamSpen210** [comment]
This is more of a compiler problem I think, needing upgrades.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2-items/issues/3891
