### ISSUE TITLE
There was an error building the puzzle Bee 2.4

### ISSUE THREAD

**Issue by Greg100x** [BEEmod/BEE2.4#751]
Console:
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198044767351\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (19,12,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 51 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 5763 (ms)

VVIS failed.

Valve Software - vvis.exe (Jun 28 2017)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt

**Comment by LautaroL20** [comment]
This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by iTom33ro** [comment]
How to verify cache file?

**Comment by LautaroL20** [comment]
Here is how: https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335
