### ISSUE TITLE
P1 Fizzlers Broken.

### ISSUE THREAD

**Issue by EmirhanBudak** [BEEmod/BEE2.4#757]
They Are broken.

**Comment by TeamSpen210** [comment]
How exactly?

**Comment by IceTudor** [comment]
Custom fizzlers? Those don't really show their textures unless you reactivate them (In P1 of course).

**Comment by LautaroL20** [comment]
@EmirhanBudak - You must post any item related stuff, into the item´s section: https://github.com/BEEmod/BEE2-items/issues

This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by EmirhanBudak** [comment]
Fizzlers Working On  Entry-Exit doors but mines not work
http://steamcommunity.com/sharedfiles/filedetails/?id=1167238735 Check this
map






2017-10-14 17:44 GMT+03:00 Lautaro <notifications@github.com>:
