### ISSUE TITLE
Music is missing in tests as of the latest update

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2.4#760]
Since the latest update, PR27, music is no longer present when testing (sound effects like fizzlers and background metal sounds are still there), regardless of the song chosen.

**Comment by LautaroL20** [comment]
I tested the PRL27 and this does not happens, so here goes my usual premade message:

This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
