### ISSUE TITLE
DEAR BEE2 TEAM

### ISSUE THREAD

**Issue by gradystudios** [BEEmod/BEE2.4#761]
for some reason when i connect the catwalk it wont work! the convayor belt and rocket turret wont work!
monitors wont work and other stuff! can you fix it? from... the happy kirby (on steam)

**Comment by gradystudios** [comment]
by the way triggers wont work

**Comment by Luke18033** [comment]
What do you mean by things "don't work"? How specifically are they broken?

**Comment by gradystudios** [comment]
i cant really say There is another thing that is broken CUBE COLOR AND SCREEN CAMRAS

**Comment by gradystudios** [comment]
they say it wont build

**Comment by gradystudios** [comment]
cube color wont work by its self

**Comment by IceTudor** [comment]
(Might help) Only connect Catwalks on corners, in cardinal directions, do not try diagonally.
The Conveyor belt isn't broken in any form, guess you have it bugged
The rocket turret is however severely broken in all versions I think.
Monitors not sure, I used them with GLaDOS (Clean) and Wheatley. Not the screen cameras tho.
Cube color has to be on the same place as the dropper, exactly the same. Same with the dropperless cube I think.
Other stuff? Explain if you wanna see if its fixable. Or if you might've done something wrong.

**Comment by ZombiePwner1** [comment]
@IceTudor The rocket turret has been reported many times and we are still unsure why it's broken it doesn't exactly help when valve removed it from the game.

**Comment by LautaroL20** [comment]
This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by gradystudios** [comment]
I DEALEATED BEE MOD THEN PUT IT BACK IN! WHAT THE HECK IS WRONG? MONITORS STILL DONT EVEN WORK! SAME FOR ROCKET TURRET! I AM DONE! RELEASE A VERSOIN THAT FIXES THIS OR IM DONE WITH IT!

**Comment by Luke18033** [comment]
None of the things you mentioned are broken for anyone else, either you're doing something wrong or your Portal 2 installation is broken somehow, in which case you'll want to try reinstalling it. (But make sure to backup your maps first!) Verifying the game files might also help, but I find it usually doesn't. As for the rocket turret, that's been broken for a while and probably won't be fixed anytime soon.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
@gradystudios, Calm your tits, nobody really cares if you are done with beemod because you re doing things wrong. Collaborators already gave you possible solutions though. Better you go and play some castlevania for the Nintendo NES....

**Comment by gradystudios** [comment]
GO KILL YOURSELF

**Comment by ZombiePwner1** [comment]
@gradystudios Please do not post offensive comments on here.

**Comment by gradystudios** [comment]
YOU GUYS STOP IT! NOTHING IS WRONG WITH PORTAL 2! AND STOP CHANGING THINGS! PS LAUTAROL20 I AM NOT A IDIOT!

**Comment by SW50000** [comment]
Should we just lock this issue?
