### ISSUE TITLE
pallette export fail

### ISSUE THREAD

**Issue by lexxone1100** [BEEmod/BEE2.4#771]
Hello,,,,,,,,,,,,,,,,,,,,,,,i just installed ver 25 of the application and it wont EXPOT my new pallete or settings to portal 2 
it also says to make sure portal 2 is not running,,,,,,,,,,,,,,,,,,it is not

**Comment by Jaxinator03** [comment]
Not sure what is wrong, but why not install Pre - Release 27? It’s more stable and might (small might) fix your issue. 

Just make sure you remove all the BEEMOD V25 files before installing the new one.

**Comment by LautaroL20** [comment]
@lexxone1100 - That should not happen with the current Pre-release 27, however once you download it you will have to do the following to ensure it will work correct:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
