### ISSUE TITLE
Portal 2 Compile map error

### ISSUE THREAD

**Issue by 91Yugo** [BEEmod/BEE2.4#778]
When i want to compile my map with bee2.4 it say "There was an error  building the puzzles" please anyone help me thank you

**Comment by LautaroL20** [comment]
@91Yugo - That clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Also, if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Make sure to save these steps in a text file in case you get similar issues in a future.

8. Happy mapmaking!

**Comment by 91Yugo** [comment]
I used the autoinstaller of bee2 and when i installed it i got the beemod
(don't know if you understand)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-09 11:17 GMT+01:00 Lautaro <notifications@github.com>:

**Comment by TeamSpen210** [comment]
There is no autoinstaller, where did you get that?

**Comment by ZombiePwner1** [comment]
@TeamSpen210 He most likely used the old beemod auto-installer. @91Yugo You most likely installed the wrong beemod as bee2.4 doesn't have an auto installer yet.
