### ISSUE TITLE
Mac version doesn't work well !!!

### ISSUE THREAD

**Issue by YELDAH** [BEEmod/BEE2.4#790]
got the latest Mac version but it can't find "/opt/local/lib/libintl.8.dylib"
can someone tell me what it is and just overall give me more information!?
five days of trying to get this to work isn't fun!

**Comment by LautaroL20** [comment]
Do not expect the Mac version to work well anytime soon. Mac version is not even in the top 10 priorities of the development of Beemod right now.

**Comment by YELDAH** [comment]
Ok if I may ask, what is the highest stable version? Afterwards I'll stop bugging you...
Unless there's bugs lol

**Comment by LautaroL20** [comment]
Its the Pre-release 27, and here are the respective links for it, below. However, if you used other beemod versions in the past, it is highly recommended to do the following steps once installed:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by YELDAH** [comment]
Thank you SO much this is really helpful!
Also, you are a very patient person👍

**Comment by YELDAH** [comment]
all I see is .exe this is really annoying now

**Comment by YELDAH** [comment]
I meant highest stable MAC version, sorry

**Comment by YELDAH** [comment]
because I had the "/opt/local/lib/libintl.8.dylib" problem I wanted to know the latest version that didn't have the problem or a way to fix it

**Comment by LautaroL20** [comment]
The latest mac version is the 23, links below:

https://github.com/BEEmod/BEE2.4/releases/download/2.4.0pr23/BEE2.4_pr23_mac.zip (App)
https://github.com/BEEmod/BEE2-items/releases/download/pr23/BEE2.4.0pr23_packages.zip (Pakages)

**Comment by YELDAH** [comment]
HAVING THE SAME PROBLEM /opt/local/lib/libintl.8.dylib

**Comment by YELDAH** [comment]
please :'(

what is /opt/local/lib/libintl.8.dylib

**Comment by YELDAH** [comment]
MRY CRAS-MES🎄...            hello?

**Comment by LautaroL20** [comment]
@YELDAH - Maybe do you meant "MRY CRASH-MESS ? Happy christmas everyone btw.

**Comment by YELDAH** [comment]
idk🎄🎄🎄🎄🎄🎄🎄🎄🎄🎄🎄🎄

**Comment by Konclan** [comment]
Is this fixed?

**Comment by LautaroL20** [comment]
Who knows, i am using windows so i do not have idea.

**Comment by Luke18033** [comment]
I used the Mac version recently, worked fine as far as I could tell.
