### ISSUE TITLE
Neurotoxic vent

### ISSUE THREAD

**Issue by endertank11** [BEEmod/BEE2.4#801]
i was testing the neurotoxin vent and it basicly dosen't work i mean i drop neurotoxin but that dosen't kill the player

**Comment by LautaroL20** [comment]
This page is only to report bugs related to the user interface of Beemod, not for stuff related to Items. To report anything related to items, please report it in the Item´s repository, here: https://github.com/BEEmod/BEE2-items/issues

Also, to make sure everything will work correct, please ensure to do the following after installing Beemod:
1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
