### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AlexBaker2648** [BEEmod/BEE2.4#812]
each time i add something and even without the items it still gives me a build error same for the styles i cant copy the portal 2 console but please try and fix this problem @TeamSpen210

**Comment by LautaroL20** [comment]
This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by AlexBaker2648** [comment]
it didn't work it kept the build error and also all the custom items are missing textures @LautaroL20

**Comment by LautaroL20** [comment]
Please, after you get the build error, open the Portal 2 Developer console and copy paste the full log here. Respect to your issue, i still think that if you do my steps following the correct order, it is not possible youll keep getting build errors. It could also be that you did not download the item´s packages which will cause issues like this. Unless your hard device is damaged.
