### ISSUE TITLE
Suggestions for Pre-28

### ISSUE THREAD

**Issue by CaliMari** [BEEmod/BEE2.4#813]
-Panel Light Bridge
-Custom Music
-Overgrown Decorations (Broken Walls,Ceiling broken with sky,etc.)
-Living Panels + Large Living Panels (Broken option with Start Reversed,working on all styles)
-Wheatley Style and Bottomless Pit
-Platforms with Portal Surface,Metal and Portal Surface with AutoPortal
-Panel AutoPortal
-Small Water Pools (Maybe in the decorations)

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Comment by CaliMari** [comment]
Oh sorry i forgot this was for bugs *facepalm* ! Can i copy those sugestions in the items repository?
