### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#820]
After loading my map in Overgrown style, with overgrown skybox. The game says There Was A Error Compiling Map.. How do you solve this?

**Comment by ZombiePwner1** [comment]
Open up the console and see what the error log says.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - That would be useless unless you tell him to paste that log here.

**Comment by Nikita74RU** [comment]
Could not execute the command:
   "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Windows gave the error message:
   "�� ������� ����� ��������� ����."

VBSP failed.

Failed to start process ("C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/)


Nick unpaused the game
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198024492974\autosave.p2c
Nick unpaused the game
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198024492974\autosave.p2c
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198024492974\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198024492974\autosave.p2c

**Comment by xGARDYx** [comment]
Are you using custom items that are not from BEE2?

**Comment by LautaroL20** [comment]
@Nikita74RU - If your map is not too big, then the cause may be the following: When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
