### ISSUE TITLE
Portal Gun ON-OFF Button Issue

### ISSUE THREAD

**Issue by PieCreeper13** [BEEmod/BEE2.4#842]
There's a glitch with the Portal Gun ON-OFF Button where if you pick up a cube then stand on the Portal Gun ON-OFF Button, the cube will freeze and can't be moved.

**Comment by TeamSpen210** [comment]
Update to PR28.

**Comment by LautaroL20** [comment]
@PieCreeper13 - Once you update to PRL28, make sure to follow these steps to ensure everything will work as it must be:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
