### ISSUE TITLE
Export Failed!

### ISSUE THREAD

**Issue by protoborg** [BEEmod/BEE2.4#847]
"Copying compiler file python36.dll failed.Ensure the PORTAL 2 is not running."

I don't imagine that is a good thing.  Also, the one time I proceeded to use the PeTI after this error, the pallet in-game had quite a few missing icons.  Those items also only displayed as an error item.  This included some of the standard items in the game like buttons.

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Note: if for some weird reason, all the instructions above did not solve your issue, please reply to this comment and i will re-open your issue report again, as well as figuring out another solution for your issue, together.**
