### ISSUE TITLE
Door Editor Models are being invisible in a "Mysterious Way" for 50s, 60s, 70s and 80s style

### ISSUE THREAD

**Issue by GamerX69** [BEEmod/BEE2.4#908]
it still works as normal, but you cant see it

![20180427135730_1](https://user-images.githubusercontent.com/38441254/39361548-47eb1498-4a23-11e8-85c1-1c73c9062de2.jpg)

**Comment by Nikita74Russian** [comment]
Why is it intentional?

**Comment by LautaroL20** [comment]
First off, that screenshot is incorrect because the model do not even displays their frames or anything, so i thought seeing at that worng picture, he was reffering to the "culling" part of its back when you rotate the view, which Spencer modified in the models on this latest release. 

This is actually the correct picture, only their selection mesh is visible while the whole model is not:
![20180501042118_1](https://user-images.githubusercontent.com/12244376/39465072-b57ad4a4-4cf7-11e8-97c0-df7316313eab.jpg)

**Comment by LautaroL20** [comment]
I will fix it this week using Crowbar, probably their QC file patch is wrong or something.

**Comment by LautaroL20** [comment]
This has been fixed for next release, commit: https://github.com/BEEmod/BEE2-items/commit/8bb007b286b7891efc7b380c9cfac68c8e2b4de0 and also this is not the section to report bugs related to items. Item section is here: https://github.com/BEEmod/BEE2-items/issues
