### ISSUE TITLE
Crash to desktop, involving ant line calculation(?)

### ISSUE THREAD

**Issue by ReikaKalseki** [BEEmod/BEE2.4#920]
I am working on a (very) large and complex chamber, and the final exit door (which is a 'vanilla' PeTI exit door) (labelled 'C' in the image) is giving me trouble. Namely that when I connect it to the two inputs (A and B), it tends to crash the editor except under very specific geometries. The problem seems to have something to do with it being unable to pathfind antlines to the door, possibly due to the observation window (though deleting that window does not rectify the situation).

Under this arrangement, it works, but moving the door (for example one tile up) causes a crash, as does placing a strip light in most nearby locations.
![https://i.imgur.com/3h8BM1J.png](https://i.imgur.com/3h8BM1J.png)

Under this arrangement, only one of the two inputs can be connected or it crashes. One would expect the antlines to follow the green arrows. (Sure enough, 'signage' type connectivity display does NOT crash).
![https://i.imgur.com/2KW9dz7.png](https://i.imgur.com/2KW9dz7.png)

**Comment by TeamSpen210** [comment]
There are a few crash bugs with antlines. Since the game is closed source, I unfortunately can't really do anything to fix it, or exactly diagnose the cause. (Fancy reading assembler?) I do know of one crash bug though, which might be your problem. When generating an antline from an item that's smaller than a full block, what the editor does is first extend the antline in a straight line to the border of a tile; only then does it start pathfinding. If you obstruct that, it promptly crashes. It doesn't crash if you totally cover a side, so it doesn't choose that position to try generating from. It may be the light strip in the second image, right of the exit door. It's inside the same block (items are centered in the block, then rotated to face a side), and obstructs one path. If you move it to be directly touching the side of the door, or push that face back like in the first image, it should work.

**Comment by ReikaKalseki** [comment]
Deleting the light strip entirely seems to have fixed it, though ingame the antlines are missing on parts of some blocks. Might this be related?

![https://i.imgur.com/lsNoCO9.jpg](https://i.imgur.com/lsNoCO9.jpg)

**Comment by TeamSpen210** [comment]
That's because I haven't yet gone and tried to implement my own arbitary pathfinding on 3D objects. So all it does is copy the antlines from the surface the panel is attached to, and move them onto the angled parts.

**Comment by ReikaKalseki** [comment]
That explains the angled wall at right, but not the one by the door, which is a plain 'vanilla' wall with nothing behind or on it.

**Comment by TeamSpen210** [comment]
You might be hitting the overlay limit - there's a limit of 512 "overlays", where each section of normal, broken or corner antline is one overlay. There's a display in the app which extracts the current count from the compile logs.

**Comment by ReikaKalseki** [comment]
How do I see that?

**Comment by TeamSpen210** [comment]
It's on the "compile options" pane.

**Comment by ReikaKalseki** [comment]
My compile options pane is very small and has nothing like that:

![https://i.imgur.com/mRLm13l.png](https://i.imgur.com/mRLm13l.png)
