### ISSUE TITLE
BEEmod not responding when exporting to "PORTAL 2".

### ISSUE THREAD

**Issue by RealDeadlyOne** [BEEmod/BEE2.4#931]
Whenever I export the changes, BEEmod freezes and never responds. I use Windows 10 Home with AMD A10, Nvidia GT620, and 8gb of RAM.

**Comment by JavierNovellon** [comment]
Where's the Portal 2 directory? This exact thing happened to me before I realised BEEmod was looking in "C:\Program Files (x86)\Steam\steamapps\common\Portal 2" which did not exist because my Steam directory is in another drive.

If this is happening to you, then the quickest way to fix it is by opening BEEmod > File > Add Game and just select the correct directory; then add a name you're comfortable with.
(That's what I did anyways)
