### ISSUE TITLE
How to reinstall BEE mod2.4pr29

### ISSUE THREAD

**Issue by zibrolta** [BEEmod/BEE2.4#933]
![20180610163758_1](https://user-images.githubusercontent.com/40142991/41202079-ce5ed728-6ccc-11e8-8da8-8d05af4f9e84.jpg)
Help me, please. I had this issue when used BEEmod today. I think that I can fix it by reinstalling BEEmod, but I don't know how to do it.

**Comment by LautaroL20** [comment]
There is a readme.txt inside the application´s zip file, read it and follow the instructions, but once you installed beemod you will have to do the following to ensure everything will work correct:

When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
