### ISSUE TITLE
Prerelease 28 and 29 fail to build maps

### ISSUE THREAD

**Issue by lcyLand** [BEEmod/BEE2.4#937]
This is a problem that many people have. It's a puzzle not building with prerelease 28 or 29.

I never copied the output, but let's just say that it could even be blank and it will still fail.

I'm trying right now to make a map that involves wall climbing. If you don't know what wall climbing is, you put a cube down to the corner of 2 walls, and put something ontop of it that's small, like a camera.

I will try pre release 27 for this, and if it does have this issue, this needs to be fixed in prerelease 30 unless you can give me a fix.

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by lcyLand** [comment]
Why close it? It’s possible that it won’t work.

**Comment by LautaroL20** [comment]
> lcyLand said: "Why close it?"

Because both pre-releases works pretty well, except for noobs that do not know how to do a clean install of Beemod for each time that a new release is out, therefore, old shit from past releases ends up messing  the P2 files resulting in "there was an error building the puzzle", and annoyiances like that. 

#PrayForNoobs

**Comment by King0191** [comment]
Woah that came out of nowhere Icy. Calm yourself

Lautaro's ways has worked for me and if its not working for you. You probably did something wrong. Or your items are placed in ways that break the map. Check the placement of items and their orientations. Make sure no items are behind/below partial blocks. etc.

**Comment by lcyLand** [comment]
it all checks out, I did all of the stuff he said, nothing works...

But this error message came through. Get your ass ready though, it's quite long.
[compile errors.txt](https://github.com/BEEmod/BEE2.4/files/2124994/compile.errors.txt)

**Comment by King0191** [comment]
> [INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"

That seems to be your issue but I dont know how to fix that. Ask Lautaro or someone

**Comment by ZombiePwner1** [comment]
@lcyLand Please no swearing there is no need for it.

**Comment by LautaroL20** [comment]
Lol it is pretty fun for me to see when noobs gets mad so easily.

**Comment by lcyLand** [comment]
Doing clean installs also really didn’t fuck up anything for me when I used older prereleases...

So, do yourself a fucking favor AND GIVE ME A FIX THAT WORKS, RATHER THAN A CLEAN INSTALL INSTRUCTION GUIDE.

NOW OPEN THIS.

**Comment by LautaroL20** [comment]
Uhmm... How about no? I am not the author of Beemod, the author is @TeamSpen210, which is the one who works on the compiler thing. I am just a collaborator.

#PrayForNoobs

**Comment by lcyLand** [comment]
well I need a fix, I even had to have my friend fucking publish one of my levels for me, I don't want everything I make to be my friend's shit anymore.

**Comment by HugoBDesigner** [comment]
In light of the [Bee2 Contributing Guidelines](https://github.com/BEEmod/BEE2-items/blob/master/.github/contributing.md), this issue is getting locked due to excessive fowl language and toxicity. Please do not repeat this behavior in future issues.

**Comment by ZombiePwner1** [comment]
@HugoBDesigner Good thinking.
