### ISSUE TITLE
Portal 2 Update 6/20/2018

### ISSUE THREAD

**Issue by Determinated888** [BEEmod/BEE2.4#940]
This is my first entry on this website so please forgive if I mess up. After the latest Portal 2 update, things in BeeMod are now no longer working. I was using BeeMod fine just earlier today, and the update is the only thing that has changed. This is the error that the developer console gave me, I am not sure what it means.
VBSP failed.

Valve Software - vbsp.exe (Mar  1 2018)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/button/weighted_black.vmf

I would appreciate any help. Thank you!

**Comment by LautaroL20** [comment]
1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by HugoBDesigner** [comment]
@LautaroL20 if you want to save some time, I made a Wiki page with the exact contents of your messages a while ago, so you can link it instead:  
https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod
