### ISSUE TITLE
I didnt uninstall bee2.4 properly and now im stuck with my old export 

### ISSUE THREAD

**Issue by AlexBaker2648** [BEEmod/BEE2.4#949]
im now stuck with my old export i cannot reinstall portal 2 because i don't want to can someone help? also my last error i did change it using the compile pane and now i have to stop making p2 levels but i can use hammer instead.

**Comment by AlexBaker2648** [comment]
oh i fixed it all i needed to do was validate the game files

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
