### ISSUE TITLE
The entrance door in the corridor 7 option from the 1950s style doesn't open at all

### ISSUE THREAD

**Issue by HumanPerson2** [BEEmod/BEE2.4#968]

**Comment by CosignCosine** [comment]
Tested on Windows 10, clean PR29 redownload and brand new test chamber, and can confirm this behavior. If you select 7: Corridor as an entrance, the door inside will not open once you get beyond the entrance fizzler.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

This issue was moved to the items page: https://github.com/BEEmod/BEE2-items/issues/2927

**Comment by LautaroL20** [comment]
@HumanPerson2 @CosignCosine This bug will be fixed when Pre-Release 34 comes out.
